[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[profile.ci]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
fuzz = { runs = 10000 }

[dependencies]
forge-std = "1.15.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
