apiVersion: cbweb3b/v1
kind: ParticipantDeployment
metadata:
  name: bank-bradesco
spec:
  scenario: "b"
  environment: local
  mode: join
  topology:
    role: commercial-bank
  bankId: bank-bradesco
  displayName: "Bradesco"
  spoke:
    id: spoke-brl
    chainId: 1338
    currency: BRL
  joinBundleRef: ../bundles/spoke-brl.bundle.yaml
  node:
    advertisedHost: host.docker.internal
    rpc:  { port: 8647 }
    ws:   { port: 8657 }
    p2p:  { port: 31305 }
    dataDir: cbweb3-data/bank-bradesco
    validator: false
  image: build
  keyProvider: kms://local-emulator
  certSource: ca://central-bank-brazil
  relay:
    endpoint: http://host.docker.internal:4000
  frontendHost: localhost
  adminUsers:
    - { role: BANK, username: bradesco-admin, password: <local-only-bootstrap> }
