apiVersion: cbweb3b/v1
kind: ParticipantDeployment
metadata:
  name: bank-davivienda
spec:
  scenario: "b"
  environment: local
  mode: join
  topology:
    role: commercial-bank
  bankId: bank-davivienda
  displayName: "Davivienda"
  spoke:
    id: spoke-cop
    chainId: 1340
    currency: COP
  joinBundleRef: ../bundles/spoke-cop.bundle.yaml
  node:
    advertisedHost: host.docker.internal
    rpc:  { port: 33947 }
    ws:   { port: 33957 }
    p2p:  { port: 56605 }
    dataDir: cbweb3-data/bank-davivienda
    validator: false
  image: build
  keyProvider: kms://local-emulator
  certSource: ca://central-bank-colombia
  relay:
    endpoint: http://localhost:7000
  frontendHost: localhost
  launcher: enable
  launcherPort: 5199
  adminUsers:
    - { role: BANK, username: admin@davivienda.colombia.com, password: davivienda-bank-local }
