apiVersion: cbweb3b/v1
kind: ParticipantDeployment
metadata:
  name: bank-bancolombia
spec:
  scenario: "b"
  environment: local
  mode: join
  topology:
    role: commercial-bank
  bankId: bank-bancolombia
  displayName: "Bancolombia"
  spoke:
    id: spoke-cop
    chainId: 1340
    currency: COP
  joinBundleRef: ../bundles/spoke-cop.bundle.yaml
  node:
    advertisedHost: host.docker.internal
    rpc:  { port: 33946 }
    ws:   { port: 33956 }
    p2p:  { port: 56604 }
    dataDir: cbweb3-data/bank-bancolombia
    validator: false
  image: build
  keyProvider: kms://local-emulator
  certSource: ca://central-bank-colombia
  relay:
    endpoint: http://localhost:7000
  frontendHost: localhost
  launcher: enable
  launcherPort: 5198
  adminUsers:
    - { role: BANK, username: admin@bancolombia.colombia.com, password: bancolombia-bank-local }
