// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// In practice callers send the refresh_token here (Keycloak logout requires it).
	AccessToken   string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// ValidateTokenResponse carries enriched JWT claims (D7 §7.4).
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Wallet        string                 `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	BankId        string                 `protobuf:"bytes,6,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	PrivacyGroup  string                 `protobuf:"bytes,7,opt,name=privacy_group,json=privacyGroup,proto3" json:"privacy_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateTokenResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ValidateTokenResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ValidateTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateTokenResponse) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *ValidateTokenResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ValidateTokenResponse) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *ValidateTokenResponse) GetPrivacyGroup() string {
	if x != nil {
		return x.PrivacyGroup
	}
	return ""
}

type RegisterParticipantRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Country         string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	BankCode        string                 `protobuf:"bytes,3,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	Role            string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	InstitutionName string                 `protobuf:"bytes,5,opt,name=institution_name,json=institutionName,proto3" json:"institution_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterParticipantRequest) Reset() {
	*x = RegisterParticipantRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterParticipantRequest) ProtoMessage() {}

func (x *RegisterParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterParticipantRequest.ProtoReflect.Descriptor instead.
func (*RegisterParticipantRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterParticipantRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterParticipantRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RegisterParticipantRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *RegisterParticipantRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterParticipantRequest) GetInstitutionName() string {
	if x != nil {
		return x.InstitutionName
	}
	return ""
}

type RegisterParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterParticipantResponse) Reset() {
	*x = RegisterParticipantResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterParticipantResponse) ProtoMessage() {}

func (x *RegisterParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterParticipantResponse.ProtoReflect.Descriptor instead.
func (*RegisterParticipantResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterParticipantResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterParticipantResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type SignTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SignTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignTransactionRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type SignTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *SignTransactionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignTransactionResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignTransactionResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type GetKYCStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCStatusRequest) Reset() {
	*x = GetKYCStatusRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCStatusRequest) ProtoMessage() {}

func (x *GetKYCStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKYCStatusRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetKYCStatusRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type GetKYCStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCStatusResponse) Reset() {
	*x = GetKYCStatusResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCStatusResponse) ProtoMessage() {}

func (x *GetKYCStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCStatusResponse.ProtoReflect.Descriptor instead.
func (*GetKYCStatusResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetKYCStatusResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetKYCStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProvisionParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // PENDING | APPROVED | FROZEN | REVOKED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionParticipantRequest) Reset() {
	*x = ProvisionParticipantRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionParticipantRequest) ProtoMessage() {}

func (x *ProvisionParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionParticipantRequest.ProtoReflect.Descriptor instead.
func (*ProvisionParticipantRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ProvisionParticipantRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ProvisionParticipantRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProvisionParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionParticipantResponse) Reset() {
	*x = ProvisionParticipantResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionParticipantResponse) ProtoMessage() {}

func (x *ProvisionParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionParticipantResponse.ProtoReflect.Descriptor instead.
func (*ProvisionParticipantResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ProvisionParticipantResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ProvisionParticipantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OnboardParticipantRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role            string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	InstitutionName string                 `protobuf:"bytes,4,opt,name=institution_name,json=institutionName,proto3" json:"institution_name,omitempty"`
	Country         string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	BankCode        string                 `protobuf:"bytes,6,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnboardParticipantRequest) Reset() {
	*x = OnboardParticipantRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardParticipantRequest) ProtoMessage() {}

func (x *OnboardParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardParticipantRequest.ProtoReflect.Descriptor instead.
func (*OnboardParticipantRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *OnboardParticipantRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OnboardParticipantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnboardParticipantRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *OnboardParticipantRequest) GetInstitutionName() string {
	if x != nil {
		return x.InstitutionName
	}
	return ""
}

func (x *OnboardParticipantRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *OnboardParticipantRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

type OnboardParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	CertPem       string                 `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	TxHash        string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// client_secret is exposed only once; caller must store it securely.
	ClientSecret  string `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardParticipantResponse) Reset() {
	*x = OnboardParticipantResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardParticipantResponse) ProtoMessage() {}

func (x *OnboardParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardParticipantResponse.ProtoReflect.Descriptor instead.
func (*OnboardParticipantResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *OnboardParticipantResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OnboardParticipantResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *OnboardParticipantResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *OnboardParticipantResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *OnboardParticipantResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type IssueLoginNonceRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// client_secret is the first-factor credential obtained at onboarding.
	ClientSecret  string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueLoginNonceRequest) Reset() {
	*x = IssueLoginNonceRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueLoginNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLoginNonceRequest) ProtoMessage() {}

func (x *IssueLoginNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLoginNonceRequest.ProtoReflect.Descriptor instead.
func (*IssueLoginNonceRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *IssueLoginNonceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueLoginNonceRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type IssueLoginNonceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nonce is hex-encoded, valid for 5 minutes.
	Nonce         string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueLoginNonceResponse) Reset() {
	*x = IssueLoginNonceResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueLoginNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLoginNonceResponse) ProtoMessage() {}

func (x *IssueLoginNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLoginNonceResponse.ProtoReflect.Descriptor instead.
func (*IssueLoginNonceResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *IssueLoginNonceResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type VerifyPKILoginRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// nonce_signature_hex is the DER-encoded ECDSA signature of SHA-256(nonce), hex-encoded.
	NonceSignatureHex string `protobuf:"bytes,2,opt,name=nonce_signature_hex,json=nonceSignatureHex,proto3" json:"nonce_signature_hex,omitempty"`
	// cert_pem is the institution's X.509 certificate issued by the Central Bank CA.
	CertPem       string `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPKILoginRequest) Reset() {
	*x = VerifyPKILoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPKILoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPKILoginRequest) ProtoMessage() {}

func (x *VerifyPKILoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPKILoginRequest.ProtoReflect.Descriptor instead.
func (*VerifyPKILoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyPKILoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyPKILoginRequest) GetNonceSignatureHex() string {
	if x != nil {
		return x.NonceSignatureHex
	}
	return ""
}

func (x *VerifyPKILoginRequest) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

type VerifyPKILoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPKILoginResponse) Reset() {
	*x = VerifyPKILoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPKILoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPKILoginResponse) ProtoMessage() {}

func (x *VerifyPKILoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPKILoginResponse.ProtoReflect.Descriptor instead.
func (*VerifyPKILoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *VerifyPKILoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyPKILoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyPKILoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *VerifyPKILoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`     // empty = all roles
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // empty = all statuses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *ListUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListUsersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstitutionName string                 `protobuf:"bytes,2,opt,name=institution_name,json=institutionName,proto3" json:"institution_name,omitempty"`
	Role            string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	WalletAddress   string                 `protobuf:"bytes,5,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Country         string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	BankCode        string                 `protobuf:"bytes,7,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *UserSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSummary) GetInstitutionName() string {
	if x != nil {
		return x.InstitutionName
	}
	return ""
}

func (x *UserSummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserSummary) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *UserSummary) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UserSummary) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *ListUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	InstitutionName string                 `protobuf:"bytes,4,opt,name=institution_name,json=institutionName,proto3" json:"institution_name,omitempty"`
	Role            string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	WalletAddress   string                 `protobuf:"bytes,7,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Country         string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	BankCode        string                 `protobuf:"bytes,9,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetInstitutionName() string {
	if x != nil {
		return x.InstitutionName
	}
	return ""
}

func (x *GetUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUserResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetUserResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetUserResponse) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

type ChangeClientSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentSecret string                 `protobuf:"bytes,2,opt,name=current_secret,json=currentSecret,proto3" json:"current_secret,omitempty"`
	NewSecret     string                 `protobuf:"bytes,3,opt,name=new_secret,json=newSecret,proto3" json:"new_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeClientSecretRequest) Reset() {
	*x = ChangeClientSecretRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeClientSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeClientSecretRequest) ProtoMessage() {}

func (x *ChangeClientSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeClientSecretRequest.ProtoReflect.Descriptor instead.
func (*ChangeClientSecretRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{27}
}

func (x *ChangeClientSecretRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeClientSecretRequest) GetCurrentSecret() string {
	if x != nil {
		return x.CurrentSecret
	}
	return ""
}

func (x *ChangeClientSecretRequest) GetNewSecret() string {
	if x != nil {
		return x.NewSecret
	}
	return ""
}

type ChangeClientSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeClientSecretResponse) Reset() {
	*x = ChangeClientSecretResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeClientSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeClientSecretResponse) ProtoMessage() {}

func (x *ChangeClientSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeClientSecretResponse.ProtoReflect.Descriptor instead.
func (*ChangeClientSecretResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{28}
}

type SubmitCredentialRequestReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PKCS#10 CSR signed with the bank's P-256 key.
	CsrPem string `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Hex-encoded uncompressed secp256k1 public key (04‖X‖Y, 65 bytes).
	BlockchainPubKeyHex string `protobuf:"bytes,2,opt,name=blockchain_pub_key_hex,json=blockchainPubKeyHex,proto3" json:"blockchain_pub_key_hex,omitempty"`
	InstitutionName     string `protobuf:"bytes,3,opt,name=institution_name,json=institutionName,proto3" json:"institution_name,omitempty"`
	Cnpj                string `protobuf:"bytes,4,opt,name=cnpj,proto3" json:"cnpj,omitempty"`
	BankCode            string `protobuf:"bytes,5,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	Country             string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Role                string `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Email               string `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Username            string `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubmitCredentialRequestReq) Reset() {
	*x = SubmitCredentialRequestReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCredentialRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCredentialRequestReq) ProtoMessage() {}

func (x *SubmitCredentialRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCredentialRequestReq.ProtoReflect.Descriptor instead.
func (*SubmitCredentialRequestReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{29}
}

func (x *SubmitCredentialRequestReq) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetBlockchainPubKeyHex() string {
	if x != nil {
		return x.BlockchainPubKeyHex
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetInstitutionName() string {
	if x != nil {
		return x.InstitutionName
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetCnpj() string {
	if x != nil {
		return x.Cnpj
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitCredentialRequestReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SubmitCredentialRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // CREDENTIAL_REQUESTED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCredentialRequestResp) Reset() {
	*x = SubmitCredentialRequestResp{}
	mi := &file_auth_v1_auth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCredentialRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCredentialRequestResp) ProtoMessage() {}

func (x *SubmitCredentialRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCredentialRequestResp.ProtoReflect.Descriptor instead.
func (*SubmitCredentialRequestResp) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{30}
}

func (x *SubmitCredentialRequestResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitCredentialRequestResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitCredentialRequestResp) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *SubmitCredentialRequestResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOnboardingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnboardingStatusRequest) Reset() {
	*x = GetOnboardingStatusRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingStatusRequest) ProtoMessage() {}

func (x *GetOnboardingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOnboardingStatusRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{31}
}

func (x *GetOnboardingStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetOnboardingStatusResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status    string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // CREDENTIAL_REQUESTED | KYC_APPROVED | ACTIVE
	// pop_nonce is only populated when status = KYC_APPROVED.
	PopNonce      string `protobuf:"bytes,4,opt,name=pop_nonce,json=popNonce,proto3" json:"pop_nonce,omitempty"`
	WalletAddress string `protobuf:"bytes,5,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnboardingStatusResponse) Reset() {
	*x = GetOnboardingStatusResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnboardingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnboardingStatusResponse) ProtoMessage() {}

func (x *GetOnboardingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnboardingStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOnboardingStatusResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{32}
}

func (x *GetOnboardingStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetOnboardingStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOnboardingStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOnboardingStatusResponse) GetPopNonce() string {
	if x != nil {
		return x.PopNonce
	}
	return ""
}

func (x *GetOnboardingStatusResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type CompleteOnboardingRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Hex-encoded 65-byte recoverable secp256k1 signature of SHA-256(pop_nonce).
	PopSignatureHex string `protobuf:"bytes,3,opt,name=pop_signature_hex,json=popSignatureHex,proto3" json:"pop_signature_hex,omitempty"`
	// Hex-encoded uncompressed secp256k1 public key (must match credential request).
	BlockchainPubKeyHex string `protobuf:"bytes,4,opt,name=blockchain_pub_key_hex,json=blockchainPubKeyHex,proto3" json:"blockchain_pub_key_hex,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{33}
}

func (x *CompleteOnboardingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetPopSignatureHex() string {
	if x != nil {
		return x.PopSignatureHex
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetBlockchainPubKeyHex() string {
	if x != nil {
		return x.BlockchainPubKeyHex
	}
	return ""
}

type CompleteOnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	CertPem       string                 `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	TxHash        string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // ACTIVE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingResponse) Reset() {
	*x = CompleteOnboardingResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingResponse) ProtoMessage() {}

func (x *CompleteOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingResponse.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{34}
}

func (x *CompleteOnboardingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\">\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x95\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x9c\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\"7\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"/\n" +
	"\x13RevokeTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xcf\x01\n" +
	"\x15ValidateTokenResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x16\n" +
	"\x06wallet\x18\x04 \x01(\tR\x06wallet\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x17\n" +
	"\abank_id\x18\x06 \x01(\tR\x06bankId\x12#\n" +
	"\rprivacy_group\x18\a \x01(\tR\fprivacyGroup\"\xb5\x01\n" +
	"\x1aRegisterParticipantRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1b\n" +
	"\tbank_code\x18\x03 \x01(\tR\bbankCode\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12)\n" +
	"\x10institution_name\x18\x05 \x01(\tR\x0finstitutionName\"]\n" +
	"\x1bRegisterParticipantResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\"I\n" +
	"\x16SignTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"j\n" +
	"\x17SignTransactionResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"/\n" +
	"\x13GetKYCStatusRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"H\n" +
	"\x14GetKYCStatusResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"\x1bProvisionParticipantRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"P\n" +
	"\x1cProvisionParticipantResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc3\x01\n" +
	"\x19OnboardParticipantRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12)\n" +
	"\x10institution_name\x18\x04 \x01(\tR\x0finstitutionName\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1b\n" +
	"\tbank_code\x18\x06 \x01(\tR\bbankCode\"\xb5\x01\n" +
	"\x1aOnboardParticipantResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x19\n" +
	"\bcert_pem\x18\x03 \x01(\tR\acertPem\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\"V\n" +
	"\x16IssueLoginNonceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\"/\n" +
	"\x17IssueLoginNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"{\n" +
	"\x15VerifyPKILoginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x13nonce_signature_hex\x18\x02 \x01(\tR\x11nonceSignatureHex\x12\x19\n" +
	"\bcert_pem\x18\x03 \x01(\tR\acertPem\"\x9e\x01\n" +
	"\x16VerifyPKILoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\">\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xdb\x01\n" +
	"\vUserSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10institution_name\x18\x02 \x01(\tR\x0finstitutionName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0ewallet_address\x18\x05 \x01(\tR\rwalletAddress\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1b\n" +
	"\tbank_code\x18\a \x01(\tR\bbankCode\"U\n" +
	"\x11ListUsersResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.auth.v1.UserSummaryR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x91\x02\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12)\n" +
	"\x10institution_name\x18\x04 \x01(\tR\x0finstitutionName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0ewallet_address\x18\a \x01(\tR\rwalletAddress\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1b\n" +
	"\tbank_code\x18\t \x01(\tR\bbankCode\"z\n" +
	"\x19ChangeClientSecretRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ecurrent_secret\x18\x02 \x01(\tR\rcurrentSecret\x12\x1d\n" +
	"\n" +
	"new_secret\x18\x03 \x01(\tR\tnewSecret\"\x1c\n" +
	"\x1aChangeClientSecretResponse\"\xa6\x02\n" +
	"\x1aSubmitCredentialRequestReq\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\tR\x06csrPem\x123\n" +
	"\x16blockchain_pub_key_hex\x18\x02 \x01(\tR\x13blockchainPubKeyHex\x12)\n" +
	"\x10institution_name\x18\x03 \x01(\tR\x0finstitutionName\x12\x12\n" +
	"\x04cnpj\x18\x04 \x01(\tR\x04cnpj\x12\x1b\n" +
	"\tbank_code\x18\x05 \x01(\tR\bbankCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\"\x94\x01\n" +
	"\x1bSubmitCredentialRequestResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\";\n" +
	"\x1aGetOnboardingStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xb1\x01\n" +
	"\x1bGetOnboardingStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tpop_nonce\x18\x04 \x01(\tR\bpopNonce\x12%\n" +
	"\x0ewallet_address\x18\x05 \x01(\tR\rwalletAddress\"\xb4\x01\n" +
	"\x19CompleteOnboardingRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x11pop_signature_hex\x18\x03 \x01(\tR\x0fpopSignatureHex\x123\n" +
	"\x16blockchain_pub_key_hex\x18\x04 \x01(\tR\x13blockchainPubKeyHex\"\xcd\x01\n" +
	"\x1aCompleteOnboardingResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x19\n" +
	"\bcert_pem\x18\x03 \x01(\tR\acertPem\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status2\xa6\v\n" +
	"\vAuthService\x126\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponse\x12H\n" +
	"\vRevokeToken\x12\x1b.auth.v1.RevokeTokenRequest\x1a\x1c.auth.v1.RevokeTokenResponse\x12N\n" +
	"\rValidateToken\x12\x1d.auth.v1.ValidateTokenRequest\x1a\x1e.auth.v1.ValidateTokenResponse\x12`\n" +
	"\x13RegisterParticipant\x12#.auth.v1.RegisterParticipantRequest\x1a$.auth.v1.RegisterParticipantResponse\x12T\n" +
	"\x0fSignTransaction\x12\x1f.auth.v1.SignTransactionRequest\x1a .auth.v1.SignTransactionResponse\x12K\n" +
	"\fGetKYCStatus\x12\x1c.auth.v1.GetKYCStatusRequest\x1a\x1d.auth.v1.GetKYCStatusResponse\x12c\n" +
	"\x14ProvisionParticipant\x12$.auth.v1.ProvisionParticipantRequest\x1a%.auth.v1.ProvisionParticipantResponse\x12]\n" +
	"\x12OnboardParticipant\x12\".auth.v1.OnboardParticipantRequest\x1a#.auth.v1.OnboardParticipantResponse\x12B\n" +
	"\tListUsers\x12\x19.auth.v1.ListUsersRequest\x1a\x1a.auth.v1.ListUsersResponse\x12<\n" +
	"\aGetUser\x12\x17.auth.v1.GetUserRequest\x1a\x18.auth.v1.GetUserResponse\x12T\n" +
	"\x0fIssueLoginNonce\x12\x1f.auth.v1.IssueLoginNonceRequest\x1a .auth.v1.IssueLoginNonceResponse\x12Q\n" +
	"\x0eVerifyPKILogin\x12\x1e.auth.v1.VerifyPKILoginRequest\x1a\x1f.auth.v1.VerifyPKILoginResponse\x12]\n" +
	"\x12ChangeClientSecret\x12\".auth.v1.ChangeClientSecretRequest\x1a#.auth.v1.ChangeClientSecretResponse\x12d\n" +
	"\x17SubmitCredentialRequest\x12#.auth.v1.SubmitCredentialRequestReq\x1a$.auth.v1.SubmitCredentialRequestResp\x12`\n" +
	"\x13GetOnboardingStatus\x12#.auth.v1.GetOnboardingStatusRequest\x1a$.auth.v1.GetOnboardingStatusResponse\x12]\n" +
	"\x12CompleteOnboarding\x12\".auth.v1.CompleteOnboardingRequest\x1a#.auth.v1.CompleteOnboardingResponseBOZMgithub.com/LACNetNetworks/cbweb3-platform/backend/shared/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_auth_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                 // 0: auth.v1.LoginRequest
	(*LoginResponse)(nil),                // 1: auth.v1.LoginResponse
	(*RefreshTokenRequest)(nil),          // 2: auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),         // 3: auth.v1.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),           // 4: auth.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),          // 5: auth.v1.RevokeTokenResponse
	(*ValidateTokenRequest)(nil),         // 6: auth.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),        // 7: auth.v1.ValidateTokenResponse
	(*RegisterParticipantRequest)(nil),   // 8: auth.v1.RegisterParticipantRequest
	(*RegisterParticipantResponse)(nil),  // 9: auth.v1.RegisterParticipantResponse
	(*SignTransactionRequest)(nil),       // 10: auth.v1.SignTransactionRequest
	(*SignTransactionResponse)(nil),      // 11: auth.v1.SignTransactionResponse
	(*GetKYCStatusRequest)(nil),          // 12: auth.v1.GetKYCStatusRequest
	(*GetKYCStatusResponse)(nil),         // 13: auth.v1.GetKYCStatusResponse
	(*ProvisionParticipantRequest)(nil),  // 14: auth.v1.ProvisionParticipantRequest
	(*ProvisionParticipantResponse)(nil), // 15: auth.v1.ProvisionParticipantResponse
	(*OnboardParticipantRequest)(nil),    // 16: auth.v1.OnboardParticipantRequest
	(*OnboardParticipantResponse)(nil),   // 17: auth.v1.OnboardParticipantResponse
	(*IssueLoginNonceRequest)(nil),       // 18: auth.v1.IssueLoginNonceRequest
	(*IssueLoginNonceResponse)(nil),      // 19: auth.v1.IssueLoginNonceResponse
	(*VerifyPKILoginRequest)(nil),        // 20: auth.v1.VerifyPKILoginRequest
	(*VerifyPKILoginResponse)(nil),       // 21: auth.v1.VerifyPKILoginResponse
	(*ListUsersRequest)(nil),             // 22: auth.v1.ListUsersRequest
	(*UserSummary)(nil),                  // 23: auth.v1.UserSummary
	(*ListUsersResponse)(nil),            // 24: auth.v1.ListUsersResponse
	(*GetUserRequest)(nil),               // 25: auth.v1.GetUserRequest
	(*GetUserResponse)(nil),              // 26: auth.v1.GetUserResponse
	(*ChangeClientSecretRequest)(nil),    // 27: auth.v1.ChangeClientSecretRequest
	(*ChangeClientSecretResponse)(nil),   // 28: auth.v1.ChangeClientSecretResponse
	(*SubmitCredentialRequestReq)(nil),   // 29: auth.v1.SubmitCredentialRequestReq
	(*SubmitCredentialRequestResp)(nil),  // 30: auth.v1.SubmitCredentialRequestResp
	(*GetOnboardingStatusRequest)(nil),   // 31: auth.v1.GetOnboardingStatusRequest
	(*GetOnboardingStatusResponse)(nil),  // 32: auth.v1.GetOnboardingStatusResponse
	(*CompleteOnboardingRequest)(nil),    // 33: auth.v1.CompleteOnboardingRequest
	(*CompleteOnboardingResponse)(nil),   // 34: auth.v1.CompleteOnboardingResponse
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	23, // 0: auth.v1.ListUsersResponse.users:type_name -> auth.v1.UserSummary
	0,  // 1: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	2,  // 2: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	4,  // 3: auth.v1.AuthService.RevokeToken:input_type -> auth.v1.RevokeTokenRequest
	6,  // 4: auth.v1.AuthService.ValidateToken:input_type -> auth.v1.ValidateTokenRequest
	8,  // 5: auth.v1.AuthService.RegisterParticipant:input_type -> auth.v1.RegisterParticipantRequest
	10, // 6: auth.v1.AuthService.SignTransaction:input_type -> auth.v1.SignTransactionRequest
	12, // 7: auth.v1.AuthService.GetKYCStatus:input_type -> auth.v1.GetKYCStatusRequest
	14, // 8: auth.v1.AuthService.ProvisionParticipant:input_type -> auth.v1.ProvisionParticipantRequest
	16, // 9: auth.v1.AuthService.OnboardParticipant:input_type -> auth.v1.OnboardParticipantRequest
	22, // 10: auth.v1.AuthService.ListUsers:input_type -> auth.v1.ListUsersRequest
	25, // 11: auth.v1.AuthService.GetUser:input_type -> auth.v1.GetUserRequest
	18, // 12: auth.v1.AuthService.IssueLoginNonce:input_type -> auth.v1.IssueLoginNonceRequest
	20, // 13: auth.v1.AuthService.VerifyPKILogin:input_type -> auth.v1.VerifyPKILoginRequest
	27, // 14: auth.v1.AuthService.ChangeClientSecret:input_type -> auth.v1.ChangeClientSecretRequest
	29, // 15: auth.v1.AuthService.SubmitCredentialRequest:input_type -> auth.v1.SubmitCredentialRequestReq
	31, // 16: auth.v1.AuthService.GetOnboardingStatus:input_type -> auth.v1.GetOnboardingStatusRequest
	33, // 17: auth.v1.AuthService.CompleteOnboarding:input_type -> auth.v1.CompleteOnboardingRequest
	1,  // 18: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	3,  // 19: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	5,  // 20: auth.v1.AuthService.RevokeToken:output_type -> auth.v1.RevokeTokenResponse
	7,  // 21: auth.v1.AuthService.ValidateToken:output_type -> auth.v1.ValidateTokenResponse
	9,  // 22: auth.v1.AuthService.RegisterParticipant:output_type -> auth.v1.RegisterParticipantResponse
	11, // 23: auth.v1.AuthService.SignTransaction:output_type -> auth.v1.SignTransactionResponse
	13, // 24: auth.v1.AuthService.GetKYCStatus:output_type -> auth.v1.GetKYCStatusResponse
	15, // 25: auth.v1.AuthService.ProvisionParticipant:output_type -> auth.v1.ProvisionParticipantResponse
	17, // 26: auth.v1.AuthService.OnboardParticipant:output_type -> auth.v1.OnboardParticipantResponse
	24, // 27: auth.v1.AuthService.ListUsers:output_type -> auth.v1.ListUsersResponse
	26, // 28: auth.v1.AuthService.GetUser:output_type -> auth.v1.GetUserResponse
	19, // 29: auth.v1.AuthService.IssueLoginNonce:output_type -> auth.v1.IssueLoginNonceResponse
	21, // 30: auth.v1.AuthService.VerifyPKILogin:output_type -> auth.v1.VerifyPKILoginResponse
	28, // 31: auth.v1.AuthService.ChangeClientSecret:output_type -> auth.v1.ChangeClientSecretResponse
	30, // 32: auth.v1.AuthService.SubmitCredentialRequest:output_type -> auth.v1.SubmitCredentialRequestResp
	32, // 33: auth.v1.AuthService.GetOnboardingStatus:output_type -> auth.v1.GetOnboardingStatusResponse
	34, // 34: auth.v1.AuthService.CompleteOnboarding:output_type -> auth.v1.CompleteOnboardingResponse
	18, // [18:35] is the sub-list for method output_type
	1,  // [1:18] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
