// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Login_FullMethodName                   = "/auth.v1.AuthService/Login"
	AuthService_RefreshToken_FullMethodName            = "/auth.v1.AuthService/RefreshToken"
	AuthService_RevokeToken_FullMethodName             = "/auth.v1.AuthService/RevokeToken"
	AuthService_ValidateToken_FullMethodName           = "/auth.v1.AuthService/ValidateToken"
	AuthService_RegisterParticipant_FullMethodName     = "/auth.v1.AuthService/RegisterParticipant"
	AuthService_SignTransaction_FullMethodName         = "/auth.v1.AuthService/SignTransaction"
	AuthService_GetKYCStatus_FullMethodName            = "/auth.v1.AuthService/GetKYCStatus"
	AuthService_ProvisionParticipant_FullMethodName    = "/auth.v1.AuthService/ProvisionParticipant"
	AuthService_OnboardParticipant_FullMethodName      = "/auth.v1.AuthService/OnboardParticipant"
	AuthService_ListUsers_FullMethodName               = "/auth.v1.AuthService/ListUsers"
	AuthService_GetUser_FullMethodName                 = "/auth.v1.AuthService/GetUser"
	AuthService_IssueLoginNonce_FullMethodName         = "/auth.v1.AuthService/IssueLoginNonce"
	AuthService_VerifyPKILogin_FullMethodName          = "/auth.v1.AuthService/VerifyPKILogin"
	AuthService_ChangeClientSecret_FullMethodName      = "/auth.v1.AuthService/ChangeClientSecret"
	AuthService_SubmitCredentialRequest_FullMethodName = "/auth.v1.AuthService/SubmitCredentialRequest"
	AuthService_GetOnboardingStatus_FullMethodName     = "/auth.v1.AuthService/GetOnboardingStatus"
	AuthService_CompleteOnboarding_FullMethodName      = "/auth.v1.AuthService/CompleteOnboarding"
	AuthService_CreateOnboardingKey_FullMethodName     = "/auth.v1.AuthService/CreateOnboardingKey"
	AuthService_SignOnboardingPoP_FullMethodName       = "/auth.v1.AuthService/SignOnboardingPoP"
	AuthService_GetOnboardingKey_FullMethodName        = "/auth.v1.AuthService/GetOnboardingKey"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	RegisterParticipant(ctx context.Context, in *RegisterParticipantRequest, opts ...grpc.CallOption) (*RegisterParticipantResponse, error)
	SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error)
	GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error)
	ProvisionParticipant(ctx context.Context, in *ProvisionParticipantRequest, opts ...grpc.CallOption) (*ProvisionParticipantResponse, error)
	// Deprecated: use SubmitCredentialRequest + CompleteOnboarding instead.
	OnboardParticipant(ctx context.Context, in *OnboardParticipantRequest, opts ...grpc.CallOption) (*OnboardParticipantResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	IssueLoginNonce(ctx context.Context, in *IssueLoginNonceRequest, opts ...grpc.CallOption) (*IssueLoginNonceResponse, error)
	VerifyPKILogin(ctx context.Context, in *VerifyPKILoginRequest, opts ...grpc.CallOption) (*VerifyPKILoginResponse, error)
	ChangeClientSecret(ctx context.Context, in *ChangeClientSecretRequest, opts ...grpc.CallOption) (*ChangeClientSecretResponse, error)
	// New onboarding flow (3-phase PKI + Blockchain)
	SubmitCredentialRequest(ctx context.Context, in *SubmitCredentialRequestReq, opts ...grpc.CallOption) (*SubmitCredentialRequestResp, error)
	GetOnboardingStatus(ctx context.Context, in *GetOnboardingStatusRequest, opts ...grpc.CallOption) (*GetOnboardingStatusResponse, error)
	CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*CompleteOnboardingResponse, error)
	// KMS onboarding helpers (Commercial Bank gateway → local auth service)
	CreateOnboardingKey(ctx context.Context, in *CreateOnboardingKeyRequest, opts ...grpc.CallOption) (*CreateOnboardingKeyResponse, error)
	SignOnboardingPoP(ctx context.Context, in *SignOnboardingPoPRequest, opts ...grpc.CallOption) (*SignOnboardingPoPResponse, error)
	GetOnboardingKey(ctx context.Context, in *GetOnboardingKeyRequest, opts ...grpc.CallOption) (*GetOnboardingKeyResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterParticipant(ctx context.Context, in *RegisterParticipantRequest, opts ...grpc.CallOption) (*RegisterParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterParticipantResponse)
	err := c.cc.Invoke(ctx, AuthService_RegisterParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignTransactionResponse)
	err := c.cc.Invoke(ctx, AuthService_SignTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCStatusResponse)
	err := c.cc.Invoke(ctx, AuthService_GetKYCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ProvisionParticipant(ctx context.Context, in *ProvisionParticipantRequest, opts ...grpc.CallOption) (*ProvisionParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionParticipantResponse)
	err := c.cc.Invoke(ctx, AuthService_ProvisionParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) OnboardParticipant(ctx context.Context, in *OnboardParticipantRequest, opts ...grpc.CallOption) (*OnboardParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnboardParticipantResponse)
	err := c.cc.Invoke(ctx, AuthService_OnboardParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, AuthService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) IssueLoginNonce(ctx context.Context, in *IssueLoginNonceRequest, opts ...grpc.CallOption) (*IssueLoginNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueLoginNonceResponse)
	err := c.cc.Invoke(ctx, AuthService_IssueLoginNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyPKILogin(ctx context.Context, in *VerifyPKILoginRequest, opts ...grpc.CallOption) (*VerifyPKILoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPKILoginResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyPKILogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeClientSecret(ctx context.Context, in *ChangeClientSecretRequest, opts ...grpc.CallOption) (*ChangeClientSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeClientSecretResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeClientSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SubmitCredentialRequest(ctx context.Context, in *SubmitCredentialRequestReq, opts ...grpc.CallOption) (*SubmitCredentialRequestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCredentialRequestResp)
	err := c.cc.Invoke(ctx, AuthService_SubmitCredentialRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetOnboardingStatus(ctx context.Context, in *GetOnboardingStatusRequest, opts ...grpc.CallOption) (*GetOnboardingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnboardingStatusResponse)
	err := c.cc.Invoke(ctx, AuthService_GetOnboardingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*CompleteOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteOnboardingResponse)
	err := c.cc.Invoke(ctx, AuthService_CompleteOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateOnboardingKey(ctx context.Context, in *CreateOnboardingKeyRequest, opts ...grpc.CallOption) (*CreateOnboardingKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOnboardingKeyResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateOnboardingKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignOnboardingPoP(ctx context.Context, in *SignOnboardingPoPRequest, opts ...grpc.CallOption) (*SignOnboardingPoPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignOnboardingPoPResponse)
	err := c.cc.Invoke(ctx, AuthService_SignOnboardingPoP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetOnboardingKey(ctx context.Context, in *GetOnboardingKeyRequest, opts ...grpc.CallOption) (*GetOnboardingKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnboardingKeyResponse)
	err := c.cc.Invoke(ctx, AuthService_GetOnboardingKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations should embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	RegisterParticipant(context.Context, *RegisterParticipantRequest) (*RegisterParticipantResponse, error)
	SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionResponse, error)
	GetKYCStatus(context.Context, *GetKYCStatusRequest) (*GetKYCStatusResponse, error)
	ProvisionParticipant(context.Context, *ProvisionParticipantRequest) (*ProvisionParticipantResponse, error)
	// Deprecated: use SubmitCredentialRequest + CompleteOnboarding instead.
	OnboardParticipant(context.Context, *OnboardParticipantRequest) (*OnboardParticipantResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	IssueLoginNonce(context.Context, *IssueLoginNonceRequest) (*IssueLoginNonceResponse, error)
	VerifyPKILogin(context.Context, *VerifyPKILoginRequest) (*VerifyPKILoginResponse, error)
	ChangeClientSecret(context.Context, *ChangeClientSecretRequest) (*ChangeClientSecretResponse, error)
	// New onboarding flow (3-phase PKI + Blockchain)
	SubmitCredentialRequest(context.Context, *SubmitCredentialRequestReq) (*SubmitCredentialRequestResp, error)
	GetOnboardingStatus(context.Context, *GetOnboardingStatusRequest) (*GetOnboardingStatusResponse, error)
	CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*CompleteOnboardingResponse, error)
	// KMS onboarding helpers (Commercial Bank gateway → local auth service)
	CreateOnboardingKey(context.Context, *CreateOnboardingKeyRequest) (*CreateOnboardingKeyResponse, error)
	SignOnboardingPoP(context.Context, *SignOnboardingPoPRequest) (*SignOnboardingPoPResponse, error)
	GetOnboardingKey(context.Context, *GetOnboardingKeyRequest) (*GetOnboardingKeyResponse, error)
}

// UnimplementedAuthServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedAuthServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthServiceServer) RegisterParticipant(context.Context, *RegisterParticipantRequest) (*RegisterParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterParticipant not implemented")
}
func (UnimplementedAuthServiceServer) SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignTransaction not implemented")
}
func (UnimplementedAuthServiceServer) GetKYCStatus(context.Context, *GetKYCStatusRequest) (*GetKYCStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKYCStatus not implemented")
}
func (UnimplementedAuthServiceServer) ProvisionParticipant(context.Context, *ProvisionParticipantRequest) (*ProvisionParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionParticipant not implemented")
}
func (UnimplementedAuthServiceServer) OnboardParticipant(context.Context, *OnboardParticipantRequest) (*OnboardParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnboardParticipant not implemented")
}
func (UnimplementedAuthServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedAuthServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAuthServiceServer) IssueLoginNonce(context.Context, *IssueLoginNonceRequest) (*IssueLoginNonceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueLoginNonce not implemented")
}
func (UnimplementedAuthServiceServer) VerifyPKILogin(context.Context, *VerifyPKILoginRequest) (*VerifyPKILoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPKILogin not implemented")
}
func (UnimplementedAuthServiceServer) ChangeClientSecret(context.Context, *ChangeClientSecretRequest) (*ChangeClientSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeClientSecret not implemented")
}
func (UnimplementedAuthServiceServer) SubmitCredentialRequest(context.Context, *SubmitCredentialRequestReq) (*SubmitCredentialRequestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCredentialRequest not implemented")
}
func (UnimplementedAuthServiceServer) GetOnboardingStatus(context.Context, *GetOnboardingStatusRequest) (*GetOnboardingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnboardingStatus not implemented")
}
func (UnimplementedAuthServiceServer) CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*CompleteOnboardingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOnboarding not implemented")
}
func (UnimplementedAuthServiceServer) CreateOnboardingKey(context.Context, *CreateOnboardingKeyRequest) (*CreateOnboardingKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOnboardingKey not implemented")
}
func (UnimplementedAuthServiceServer) SignOnboardingPoP(context.Context, *SignOnboardingPoPRequest) (*SignOnboardingPoPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignOnboardingPoP not implemented")
}
func (UnimplementedAuthServiceServer) GetOnboardingKey(context.Context, *GetOnboardingKeyRequest) (*GetOnboardingKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnboardingKey not implemented")
}
func (UnimplementedAuthServiceServer) testEmbeddedByValue() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterParticipant(ctx, req.(*RegisterParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignTransaction(ctx, req.(*SignTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetKYCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetKYCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetKYCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetKYCStatus(ctx, req.(*GetKYCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ProvisionParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ProvisionParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ProvisionParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ProvisionParticipant(ctx, req.(*ProvisionParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_OnboardParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).OnboardParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_OnboardParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).OnboardParticipant(ctx, req.(*OnboardParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_IssueLoginNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueLoginNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IssueLoginNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_IssueLoginNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IssueLoginNonce(ctx, req.(*IssueLoginNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyPKILogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPKILoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyPKILogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyPKILogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyPKILogin(ctx, req.(*VerifyPKILoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeClientSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeClientSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeClientSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeClientSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeClientSecret(ctx, req.(*ChangeClientSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SubmitCredentialRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCredentialRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SubmitCredentialRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SubmitCredentialRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SubmitCredentialRequest(ctx, req.(*SubmitCredentialRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetOnboardingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnboardingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetOnboardingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetOnboardingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetOnboardingStatus(ctx, req.(*GetOnboardingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CompleteOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompleteOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CompleteOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompleteOnboarding(ctx, req.(*CompleteOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateOnboardingKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOnboardingKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateOnboardingKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateOnboardingKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateOnboardingKey(ctx, req.(*CreateOnboardingKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignOnboardingPoP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOnboardingPoPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignOnboardingPoP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignOnboardingPoP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignOnboardingPoP(ctx, req.(*SignOnboardingPoPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetOnboardingKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnboardingKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetOnboardingKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetOnboardingKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetOnboardingKey(ctx, req.(*GetOnboardingKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _AuthService_RevokeToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthService_ValidateToken_Handler,
		},
		{
			MethodName: "RegisterParticipant",
			Handler:    _AuthService_RegisterParticipant_Handler,
		},
		{
			MethodName: "SignTransaction",
			Handler:    _AuthService_SignTransaction_Handler,
		},
		{
			MethodName: "GetKYCStatus",
			Handler:    _AuthService_GetKYCStatus_Handler,
		},
		{
			MethodName: "ProvisionParticipant",
			Handler:    _AuthService_ProvisionParticipant_Handler,
		},
		{
			MethodName: "OnboardParticipant",
			Handler:    _AuthService_OnboardParticipant_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AuthService_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthService_GetUser_Handler,
		},
		{
			MethodName: "IssueLoginNonce",
			Handler:    _AuthService_IssueLoginNonce_Handler,
		},
		{
			MethodName: "VerifyPKILogin",
			Handler:    _AuthService_VerifyPKILogin_Handler,
		},
		{
			MethodName: "ChangeClientSecret",
			Handler:    _AuthService_ChangeClientSecret_Handler,
		},
		{
			MethodName: "SubmitCredentialRequest",
			Handler:    _AuthService_SubmitCredentialRequest_Handler,
		},
		{
			MethodName: "GetOnboardingStatus",
			Handler:    _AuthService_GetOnboardingStatus_Handler,
		},
		{
			MethodName: "CompleteOnboarding",
			Handler:    _AuthService_CompleteOnboarding_Handler,
		},
		{
			MethodName: "CreateOnboardingKey",
			Handler:    _AuthService_CreateOnboardingKey_Handler,
		},
		{
			MethodName: "SignOnboardingPoP",
			Handler:    _AuthService_SignOnboardingPoP_Handler,
		},
		{
			MethodName: "GetOnboardingKey",
			Handler:    _AuthService_GetOnboardingKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
