name: spoke-b

services:
  bank-b-frontend:
    container_name: cbweb3-bank-b-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_B}
    ports:
      - "${BANK_B_FRONTEND_PORT}:80"

  bank-d-frontend:
    container_name: cbweb3-bank-d-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_D}
    ports:
      - "${BANK_D_FRONTEND_PORT}:80"

  central-bank-b-frontend:
    container_name: cbweb3-central-bank-b-frontend
    build:
      context: .
      dockerfile: apps/governance/Dockerfile
      args:
        VITE_API_URL: ${API_CENTRAL_BANK_B}
    ports:
      - "${CENTRAL_BANK_B_FRONTEND_PORT}:80"