name: spoke-all

services:
  bank-a-frontend:
    container_name: cbweb3-bank-a-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_A}
        VITE_PORTAL_OWNER: ${BANK_A_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_A_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${BANK_A_INSTITUTION_NAME}
    ports:
      - "${BANK_A_FRONTEND_PORT}:80"

  bank-b-frontend:
    container_name: cbweb3-bank-b-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_B}
        VITE_PORTAL_OWNER: ${BANK_B_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_B_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${BANK_B_INSTITUTION_NAME}
    ports:
      - "${BANK_B_FRONTEND_PORT}:80"

  bank-c-frontend:
    container_name: cbweb3-bank-c-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_C}
        VITE_PORTAL_OWNER: ${BANK_C_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_A_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${BANK_C_INSTITUTION_NAME}
    ports:
      - "${BANK_C_FRONTEND_PORT}:80"

  bank-d-frontend:
    container_name: cbweb3-bank-d-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_D}
        VITE_PORTAL_OWNER: ${BANK_D_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_B_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${BANK_D_INSTITUTION_NAME}
    ports:
      - "${BANK_D_FRONTEND_PORT}:80"

  central-bank-a-frontend:
    container_name: cbweb3-central-bank-a-frontend
    build:
      context: .
      dockerfile: apps/governance/Dockerfile
      args:
        VITE_API_URL: ${API_CENTRAL_BANK_A}
        VITE_PORTAL_OWNER: ${CENTRAL_BANK_A_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_A_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${CENTRAL_BANK_A_INSTITUTION_NAME}
    ports:
      - "${CENTRAL_BANK_A_FRONTEND_PORT}:80"

  central-bank-b-frontend:
    container_name: cbweb3-central-bank-b-frontend
    build:
      context: .
      dockerfile: apps/governance/Dockerfile
      args:
        VITE_API_URL: ${API_CENTRAL_BANK_B}
        VITE_PORTAL_OWNER: ${CENTRAL_BANK_B_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_B_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${CENTRAL_BANK_B_INSTITUTION_NAME}
    ports:
      - "${CENTRAL_BANK_B_FRONTEND_PORT}:80"