// SPDX-License-Identifier: Apache-2.0

// Package domain defines the LPFeeEvent model for cooperative fee distribution (FR-005 / data-model.md §1.2).
package domain

import "time"

// LPFeeEvent is an append-only record of each swap fee generated by the AMM pool.
// The Distribution field is a JSONB snapshot of each active LP's percentage share
// at the moment of the swap (e.g. {"lp_bcb": "60.0000", "lp_fed": "40.0000"}).
// Partitioned monthly by created_at following the PoolStateReading convention.
type LPFeeEvent struct {
	EventID      string    `gorm:"primaryKey;column:event_id;type:varchar(64)"`
	PoolPair     string    `gorm:"column:pool_pair;not null;index"`
	SwapOrderID  string    `gorm:"column:swap_order_id;index"`
	FeeAmountA   string    `gorm:"column:fee_amount_a;not null;default:0"`
	FeeAmountB   string    `gorm:"column:fee_amount_b;not null;default:0"`
	Distribution string    `gorm:"column:distribution;not null;type:jsonb"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;autoCreateTime"`
}

// TableName returns the GORM table name.
func (LPFeeEvent) TableName() string { return "lp_fee_events" }
