name: scenario-b

services:
  bank-a-frontend:
    container_name: cbweb3-bank-a-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_A}
        VITE_PORTAL_OWNER: ${BANK_A_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_A_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${BANK_A_INSTITUTION_NAME}
        VITE_SCENARIO: b
    ports:
      - "${BANK_A_FRONTEND_PORT}:80"

  bank-b-frontend:
    container_name: cbweb3-bank-b-frontend
    build:
      context: .
      dockerfile: apps/bank/Dockerfile
      args:
        VITE_API_URL: ${API_BANK_B}
        VITE_PORTAL_OWNER: ${BANK_B_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_B_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${BANK_B_INSTITUTION_NAME}
        VITE_SCENARIO: b
    ports:
      - "${BANK_B_FRONTEND_PORT}:80"

  central-bank-a-frontend:
    container_name: cbweb3-central-bank-a-frontend
    build:
      context: .
      dockerfile: apps/governance/Dockerfile
      args:
        VITE_API_URL: ${API_CENTRAL_BANK_A}
        VITE_PORTAL_OWNER: ${CENTRAL_BANK_A_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_A_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${CENTRAL_BANK_A_INSTITUTION_NAME}
        VITE_SCENARIO: b
    ports:
      - "${CENTRAL_BANK_A_FRONTEND_PORT}:80"

  central-bank-a-treasury:
    container_name: cbweb3-central-bank-a-treasury
    build:
      context: .
      dockerfile: apps/treasury/Dockerfile
      args:
        VITE_API_BASE_URL: ${API_CENTRAL_BANK_A}
        VITE_FIAT_SYMBOL: ${SPOKE_A_FIAT_SYMBOL}
        VITE_POOL_PAIR: ${SPOKE_A_POOL_PAIR}
        VITE_INSTITUTION_NAME: ${CENTRAL_BANK_A_INSTITUTION_NAME}
        VITE_KC_CLIENT_ID: ${CENTRAL_BANK_A_KC_CLIENT_ID}
        VITE_KC_CLIENT_SECRET: ${CENTRAL_BANK_A_KC_CLIENT_SECRET}
    ports:
      - "${CENTRAL_BANK_A_TREASURY_PORT}:80"

  central-bank-b-frontend:
    container_name: cbweb3-central-bank-b-frontend
    build:
      context: .
      dockerfile: apps/governance/Dockerfile
      args:
        VITE_API_URL: ${API_CENTRAL_BANK_B}
        VITE_PORTAL_OWNER: ${CENTRAL_BANK_B_PORTAL_OWNER}
        VITE_FIAT_SYMBOL: ${SPOKE_B_FIAT_SYMBOL}
        VITE_INSTITUTION_NAME: ${CENTRAL_BANK_B_INSTITUTION_NAME}
        VITE_SCENARIO: b
    ports:
      - "${CENTRAL_BANK_B_FRONTEND_PORT}:80"

  central-bank-b-treasury:
    container_name: cbweb3-central-bank-b-treasury
    build:
      context: .
      dockerfile: apps/treasury/Dockerfile
      args:
        VITE_API_BASE_URL: ${API_CENTRAL_BANK_B}
        VITE_FIAT_SYMBOL: ${SPOKE_B_FIAT_SYMBOL}
        VITE_POOL_PAIR: ${SPOKE_B_POOL_PAIR}
        VITE_INSTITUTION_NAME: ${CENTRAL_BANK_B_INSTITUTION_NAME}
        VITE_KC_CLIENT_ID: ${CENTRAL_BANK_B_KC_CLIENT_ID}
        VITE_KC_CLIENT_SECRET: ${CENTRAL_BANK_B_KC_CLIENT_SECRET}
    ports:
      - "${CENTRAL_BANK_B_TREASURY_PORT}:80"
