// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: payment_orchestrator/v1/payment_orchestrator.proto

package paymentorchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentOrchestratorService_ProposeFXAgreement_FullMethodName    = "/payment_orchestrator.v1.PaymentOrchestratorService/ProposeFXAgreement"
	PaymentOrchestratorService_AcceptFXAgreement_FullMethodName     = "/payment_orchestrator.v1.PaymentOrchestratorService/AcceptFXAgreement"
	PaymentOrchestratorService_RejectFXAgreement_FullMethodName     = "/payment_orchestrator.v1.PaymentOrchestratorService/RejectFXAgreement"
	PaymentOrchestratorService_CancelFXAgreement_FullMethodName     = "/payment_orchestrator.v1.PaymentOrchestratorService/CancelFXAgreement"
	PaymentOrchestratorService_SettleFXAgreement_FullMethodName     = "/payment_orchestrator.v1.PaymentOrchestratorService/SettleFXAgreement"
	PaymentOrchestratorService_GetFXAgreement_FullMethodName        = "/payment_orchestrator.v1.PaymentOrchestratorService/GetFXAgreement"
	PaymentOrchestratorService_ListFXAgreements_FullMethodName      = "/payment_orchestrator.v1.PaymentOrchestratorService/ListFXAgreements"
	PaymentOrchestratorService_ListFXAgreementEvents_FullMethodName = "/payment_orchestrator.v1.PaymentOrchestratorService/ListFXAgreementEvents"
	PaymentOrchestratorService_LockHTLC_FullMethodName              = "/payment_orchestrator.v1.PaymentOrchestratorService/LockHTLC"
	PaymentOrchestratorService_LockHTLCWithHashLock_FullMethodName  = "/payment_orchestrator.v1.PaymentOrchestratorService/LockHTLCWithHashLock"
	PaymentOrchestratorService_SettleHTLC_FullMethodName            = "/payment_orchestrator.v1.PaymentOrchestratorService/SettleHTLC"
	PaymentOrchestratorService_RefundHTLC_FullMethodName            = "/payment_orchestrator.v1.PaymentOrchestratorService/RefundHTLC"
	PaymentOrchestratorService_GetHTLCStatus_FullMethodName         = "/payment_orchestrator.v1.PaymentOrchestratorService/GetHTLCStatus"
	PaymentOrchestratorService_SearchHTLC_FullMethodName            = "/payment_orchestrator.v1.PaymentOrchestratorService/SearchHTLC"
	PaymentOrchestratorService_GetBalance_FullMethodName            = "/payment_orchestrator.v1.PaymentOrchestratorService/GetBalance"
	PaymentOrchestratorService_GetFiatBalance_FullMethodName        = "/payment_orchestrator.v1.PaymentOrchestratorService/GetFiatBalance"
	PaymentOrchestratorService_RegisterDeposit_FullMethodName       = "/payment_orchestrator.v1.PaymentOrchestratorService/RegisterDeposit"
	PaymentOrchestratorService_ApproveDeposit_FullMethodName        = "/payment_orchestrator.v1.PaymentOrchestratorService/ApproveDeposit"
	PaymentOrchestratorService_RejectDeposit_FullMethodName         = "/payment_orchestrator.v1.PaymentOrchestratorService/RejectDeposit"
	PaymentOrchestratorService_RequestFiatExchange_FullMethodName   = "/payment_orchestrator.v1.PaymentOrchestratorService/RequestFiatExchange"
	PaymentOrchestratorService_ListDeposits_FullMethodName          = "/payment_orchestrator.v1.PaymentOrchestratorService/ListDeposits"
	PaymentOrchestratorService_RequestEscrow_FullMethodName         = "/payment_orchestrator.v1.PaymentOrchestratorService/RequestEscrow"
	PaymentOrchestratorService_ApproveEscrow_FullMethodName         = "/payment_orchestrator.v1.PaymentOrchestratorService/ApproveEscrow"
	PaymentOrchestratorService_RejectEscrow_FullMethodName          = "/payment_orchestrator.v1.PaymentOrchestratorService/RejectEscrow"
	PaymentOrchestratorService_ListEscrows_FullMethodName           = "/payment_orchestrator.v1.PaymentOrchestratorService/ListEscrows"
	PaymentOrchestratorService_RequestRedeem_FullMethodName         = "/payment_orchestrator.v1.PaymentOrchestratorService/RequestRedeem"
	PaymentOrchestratorService_ApproveRedeem_FullMethodName         = "/payment_orchestrator.v1.PaymentOrchestratorService/ApproveRedeem"
	PaymentOrchestratorService_RejectRedeem_FullMethodName          = "/payment_orchestrator.v1.PaymentOrchestratorService/RejectRedeem"
	PaymentOrchestratorService_ListRedeems_FullMethodName           = "/payment_orchestrator.v1.PaymentOrchestratorService/ListRedeems"
)

// PaymentOrchestratorServiceClient is the client API for PaymentOrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentOrchestratorServiceClient interface {
	// FX Agreement lifecycle
	ProposeFXAgreement(ctx context.Context, in *ProposeFXAgreementRequest, opts ...grpc.CallOption) (*ProposeFXAgreementResponse, error)
	AcceptFXAgreement(ctx context.Context, in *AcceptFXAgreementRequest, opts ...grpc.CallOption) (*AcceptFXAgreementResponse, error)
	RejectFXAgreement(ctx context.Context, in *RejectFXAgreementRequest, opts ...grpc.CallOption) (*RejectFXAgreementResponse, error)
	CancelFXAgreement(ctx context.Context, in *CancelFXAgreementRequest, opts ...grpc.CallOption) (*CancelFXAgreementResponse, error)
	SettleFXAgreement(ctx context.Context, in *SettleFXAgreementRequest, opts ...grpc.CallOption) (*SettleFXAgreementResponse, error)
	GetFXAgreement(ctx context.Context, in *GetFXAgreementRequest, opts ...grpc.CallOption) (*GetFXAgreementResponse, error)
	ListFXAgreements(ctx context.Context, in *ListFXAgreementsRequest, opts ...grpc.CallOption) (*ListFXAgreementsResponse, error)
	ListFXAgreementEvents(ctx context.Context, in *ListFXAgreementEventsRequest, opts ...grpc.CallOption) (*ListFXAgreementEventsResponse, error)
	// HTLC operations (on-chain Besu coordination)
	LockHTLC(ctx context.Context, in *LockHTLCRequest, opts ...grpc.CallOption) (*LockHTLCResponse, error)
	LockHTLCWithHashLock(ctx context.Context, in *LockHTLCWithHashLockRequest, opts ...grpc.CallOption) (*LockHTLCWithHashLockResponse, error)
	SettleHTLC(ctx context.Context, in *SettleHTLCRequest, opts ...grpc.CallOption) (*SettleHTLCResponse, error)
	RefundHTLC(ctx context.Context, in *RefundHTLCRequest, opts ...grpc.CallOption) (*RefundHTLCResponse, error)
	GetHTLCStatus(ctx context.Context, in *GetHTLCStatusRequest, opts ...grpc.CallOption) (*GetHTLCStatusResponse, error)
	SearchHTLC(ctx context.Context, in *SearchHTLCRequest, opts ...grpc.CallOption) (*SearchHTLCResponse, error)
	// tCeBM balance query
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// fCeBM balance query
	GetFiatBalance(ctx context.Context, in *GetFiatBalanceRequest, opts ...grpc.CallOption) (*GetFiatBalanceResponse, error)
	// Deposit lifecycle (fiat deposit from commercial bank → fCeBM mint)
	RegisterDeposit(ctx context.Context, in *RegisterDepositRequest, opts ...grpc.CallOption) (*RegisterDepositResponse, error)
	ApproveDeposit(ctx context.Context, in *ApproveDepositRequest, opts ...grpc.CallOption) (*ApproveDepositResponse, error)
	RejectDeposit(ctx context.Context, in *RejectDepositRequest, opts ...grpc.CallOption) (*RejectDepositResponse, error)
	RequestFiatExchange(ctx context.Context, in *RequestFiatExchangeRequest, opts ...grpc.CallOption) (*RequestFiatExchangeResponse, error)
	ListDeposits(ctx context.Context, in *ListDepositsRequest, opts ...grpc.CallOption) (*ListDepositsResponse, error)
	// Escrow lifecycle (tokenization: fCeBM → tCeBM)
	RequestEscrow(ctx context.Context, in *RequestEscrowRequest, opts ...grpc.CallOption) (*RequestEscrowResponse, error)
	ApproveEscrow(ctx context.Context, in *ApproveEscrowRequest, opts ...grpc.CallOption) (*ApproveEscrowResponse, error)
	RejectEscrow(ctx context.Context, in *RejectEscrowRequest, opts ...grpc.CallOption) (*RejectEscrowResponse, error)
	ListEscrows(ctx context.Context, in *ListEscrowsRequest, opts ...grpc.CallOption) (*ListEscrowsResponse, error)
	// Redeem lifecycle (tCeBM → fiat)
	RequestRedeem(ctx context.Context, in *RequestRedeemRequest, opts ...grpc.CallOption) (*RequestRedeemResponse, error)
	ApproveRedeem(ctx context.Context, in *ApproveRedeemRequest, opts ...grpc.CallOption) (*ApproveRedeemResponse, error)
	RejectRedeem(ctx context.Context, in *RejectRedeemRequest, opts ...grpc.CallOption) (*RejectRedeemResponse, error)
	ListRedeems(ctx context.Context, in *ListRedeemsRequest, opts ...grpc.CallOption) (*ListRedeemsResponse, error)
}

type paymentOrchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentOrchestratorServiceClient(cc grpc.ClientConnInterface) PaymentOrchestratorServiceClient {
	return &paymentOrchestratorServiceClient{cc}
}

func (c *paymentOrchestratorServiceClient) ProposeFXAgreement(ctx context.Context, in *ProposeFXAgreementRequest, opts ...grpc.CallOption) (*ProposeFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ProposeFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) AcceptFXAgreement(ctx context.Context, in *AcceptFXAgreementRequest, opts ...grpc.CallOption) (*AcceptFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_AcceptFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RejectFXAgreement(ctx context.Context, in *RejectFXAgreementRequest, opts ...grpc.CallOption) (*RejectFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RejectFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) CancelFXAgreement(ctx context.Context, in *CancelFXAgreementRequest, opts ...grpc.CallOption) (*CancelFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_CancelFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) SettleFXAgreement(ctx context.Context, in *SettleFXAgreementRequest, opts ...grpc.CallOption) (*SettleFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_SettleFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetFXAgreement(ctx context.Context, in *GetFXAgreementRequest, opts ...grpc.CallOption) (*GetFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ListFXAgreements(ctx context.Context, in *ListFXAgreementsRequest, opts ...grpc.CallOption) (*ListFXAgreementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFXAgreementsResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ListFXAgreements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ListFXAgreementEvents(ctx context.Context, in *ListFXAgreementEventsRequest, opts ...grpc.CallOption) (*ListFXAgreementEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFXAgreementEventsResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ListFXAgreementEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) LockHTLC(ctx context.Context, in *LockHTLCRequest, opts ...grpc.CallOption) (*LockHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_LockHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) LockHTLCWithHashLock(ctx context.Context, in *LockHTLCWithHashLockRequest, opts ...grpc.CallOption) (*LockHTLCWithHashLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockHTLCWithHashLockResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_LockHTLCWithHashLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) SettleHTLC(ctx context.Context, in *SettleHTLCRequest, opts ...grpc.CallOption) (*SettleHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_SettleHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RefundHTLC(ctx context.Context, in *RefundHTLCRequest, opts ...grpc.CallOption) (*RefundHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RefundHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetHTLCStatus(ctx context.Context, in *GetHTLCStatusRequest, opts ...grpc.CallOption) (*GetHTLCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHTLCStatusResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetHTLCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) SearchHTLC(ctx context.Context, in *SearchHTLCRequest, opts ...grpc.CallOption) (*SearchHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_SearchHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetFiatBalance(ctx context.Context, in *GetFiatBalanceRequest, opts ...grpc.CallOption) (*GetFiatBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFiatBalanceResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetFiatBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RegisterDeposit(ctx context.Context, in *RegisterDepositRequest, opts ...grpc.CallOption) (*RegisterDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDepositResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RegisterDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ApproveDeposit(ctx context.Context, in *ApproveDepositRequest, opts ...grpc.CallOption) (*ApproveDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveDepositResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ApproveDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RejectDeposit(ctx context.Context, in *RejectDepositRequest, opts ...grpc.CallOption) (*RejectDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectDepositResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RejectDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RequestFiatExchange(ctx context.Context, in *RequestFiatExchangeRequest, opts ...grpc.CallOption) (*RequestFiatExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestFiatExchangeResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RequestFiatExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ListDeposits(ctx context.Context, in *ListDepositsRequest, opts ...grpc.CallOption) (*ListDepositsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDepositsResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ListDeposits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RequestEscrow(ctx context.Context, in *RequestEscrowRequest, opts ...grpc.CallOption) (*RequestEscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestEscrowResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RequestEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ApproveEscrow(ctx context.Context, in *ApproveEscrowRequest, opts ...grpc.CallOption) (*ApproveEscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveEscrowResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ApproveEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RejectEscrow(ctx context.Context, in *RejectEscrowRequest, opts ...grpc.CallOption) (*RejectEscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectEscrowResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RejectEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ListEscrows(ctx context.Context, in *ListEscrowsRequest, opts ...grpc.CallOption) (*ListEscrowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEscrowsResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ListEscrows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RequestRedeem(ctx context.Context, in *RequestRedeemRequest, opts ...grpc.CallOption) (*RequestRedeemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRedeemResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RequestRedeem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ApproveRedeem(ctx context.Context, in *ApproveRedeemRequest, opts ...grpc.CallOption) (*ApproveRedeemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveRedeemResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ApproveRedeem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RejectRedeem(ctx context.Context, in *RejectRedeemRequest, opts ...grpc.CallOption) (*RejectRedeemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectRedeemResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RejectRedeem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ListRedeems(ctx context.Context, in *ListRedeemsRequest, opts ...grpc.CallOption) (*ListRedeemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRedeemsResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ListRedeems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentOrchestratorServiceServer is the server API for PaymentOrchestratorService service.
// All implementations should embed UnimplementedPaymentOrchestratorServiceServer
// for forward compatibility.
type PaymentOrchestratorServiceServer interface {
	// FX Agreement lifecycle
	ProposeFXAgreement(context.Context, *ProposeFXAgreementRequest) (*ProposeFXAgreementResponse, error)
	AcceptFXAgreement(context.Context, *AcceptFXAgreementRequest) (*AcceptFXAgreementResponse, error)
	RejectFXAgreement(context.Context, *RejectFXAgreementRequest) (*RejectFXAgreementResponse, error)
	CancelFXAgreement(context.Context, *CancelFXAgreementRequest) (*CancelFXAgreementResponse, error)
	SettleFXAgreement(context.Context, *SettleFXAgreementRequest) (*SettleFXAgreementResponse, error)
	GetFXAgreement(context.Context, *GetFXAgreementRequest) (*GetFXAgreementResponse, error)
	ListFXAgreements(context.Context, *ListFXAgreementsRequest) (*ListFXAgreementsResponse, error)
	ListFXAgreementEvents(context.Context, *ListFXAgreementEventsRequest) (*ListFXAgreementEventsResponse, error)
	// HTLC operations (on-chain Besu coordination)
	LockHTLC(context.Context, *LockHTLCRequest) (*LockHTLCResponse, error)
	LockHTLCWithHashLock(context.Context, *LockHTLCWithHashLockRequest) (*LockHTLCWithHashLockResponse, error)
	SettleHTLC(context.Context, *SettleHTLCRequest) (*SettleHTLCResponse, error)
	RefundHTLC(context.Context, *RefundHTLCRequest) (*RefundHTLCResponse, error)
	GetHTLCStatus(context.Context, *GetHTLCStatusRequest) (*GetHTLCStatusResponse, error)
	SearchHTLC(context.Context, *SearchHTLCRequest) (*SearchHTLCResponse, error)
	// tCeBM balance query
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// fCeBM balance query
	GetFiatBalance(context.Context, *GetFiatBalanceRequest) (*GetFiatBalanceResponse, error)
	// Deposit lifecycle (fiat deposit from commercial bank → fCeBM mint)
	RegisterDeposit(context.Context, *RegisterDepositRequest) (*RegisterDepositResponse, error)
	ApproveDeposit(context.Context, *ApproveDepositRequest) (*ApproveDepositResponse, error)
	RejectDeposit(context.Context, *RejectDepositRequest) (*RejectDepositResponse, error)
	RequestFiatExchange(context.Context, *RequestFiatExchangeRequest) (*RequestFiatExchangeResponse, error)
	ListDeposits(context.Context, *ListDepositsRequest) (*ListDepositsResponse, error)
	// Escrow lifecycle (tokenization: fCeBM → tCeBM)
	RequestEscrow(context.Context, *RequestEscrowRequest) (*RequestEscrowResponse, error)
	ApproveEscrow(context.Context, *ApproveEscrowRequest) (*ApproveEscrowResponse, error)
	RejectEscrow(context.Context, *RejectEscrowRequest) (*RejectEscrowResponse, error)
	ListEscrows(context.Context, *ListEscrowsRequest) (*ListEscrowsResponse, error)
	// Redeem lifecycle (tCeBM → fiat)
	RequestRedeem(context.Context, *RequestRedeemRequest) (*RequestRedeemResponse, error)
	ApproveRedeem(context.Context, *ApproveRedeemRequest) (*ApproveRedeemResponse, error)
	RejectRedeem(context.Context, *RejectRedeemRequest) (*RejectRedeemResponse, error)
	ListRedeems(context.Context, *ListRedeemsRequest) (*ListRedeemsResponse, error)
}

// UnimplementedPaymentOrchestratorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentOrchestratorServiceServer struct{}

func (UnimplementedPaymentOrchestratorServiceServer) ProposeFXAgreement(context.Context, *ProposeFXAgreementRequest) (*ProposeFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) AcceptFXAgreement(context.Context, *AcceptFXAgreementRequest) (*AcceptFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RejectFXAgreement(context.Context, *RejectFXAgreementRequest) (*RejectFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) CancelFXAgreement(context.Context, *CancelFXAgreementRequest) (*CancelFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) SettleFXAgreement(context.Context, *SettleFXAgreementRequest) (*SettleFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetFXAgreement(context.Context, *GetFXAgreementRequest) (*GetFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ListFXAgreements(context.Context, *ListFXAgreementsRequest) (*ListFXAgreementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFXAgreements not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ListFXAgreementEvents(context.Context, *ListFXAgreementEventsRequest) (*ListFXAgreementEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFXAgreementEvents not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) LockHTLC(context.Context, *LockHTLCRequest) (*LockHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) LockHTLCWithHashLock(context.Context, *LockHTLCWithHashLockRequest) (*LockHTLCWithHashLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockHTLCWithHashLock not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) SettleHTLC(context.Context, *SettleHTLCRequest) (*SettleHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RefundHTLC(context.Context, *RefundHTLCRequest) (*RefundHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetHTLCStatus(context.Context, *GetHTLCStatusRequest) (*GetHTLCStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHTLCStatus not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) SearchHTLC(context.Context, *SearchHTLCRequest) (*SearchHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetFiatBalance(context.Context, *GetFiatBalanceRequest) (*GetFiatBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiatBalance not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RegisterDeposit(context.Context, *RegisterDepositRequest) (*RegisterDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDeposit not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ApproveDeposit(context.Context, *ApproveDepositRequest) (*ApproveDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveDeposit not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RejectDeposit(context.Context, *RejectDepositRequest) (*RejectDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectDeposit not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RequestFiatExchange(context.Context, *RequestFiatExchangeRequest) (*RequestFiatExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestFiatExchange not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ListDeposits(context.Context, *ListDepositsRequest) (*ListDepositsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeposits not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RequestEscrow(context.Context, *RequestEscrowRequest) (*RequestEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestEscrow not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ApproveEscrow(context.Context, *ApproveEscrowRequest) (*ApproveEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveEscrow not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RejectEscrow(context.Context, *RejectEscrowRequest) (*RejectEscrowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectEscrow not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ListEscrows(context.Context, *ListEscrowsRequest) (*ListEscrowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEscrows not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RequestRedeem(context.Context, *RequestRedeemRequest) (*RequestRedeemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRedeem not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ApproveRedeem(context.Context, *ApproveRedeemRequest) (*ApproveRedeemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveRedeem not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RejectRedeem(context.Context, *RejectRedeemRequest) (*RejectRedeemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectRedeem not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ListRedeems(context.Context, *ListRedeemsRequest) (*ListRedeemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRedeems not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) testEmbeddedByValue() {}

// UnsafePaymentOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentOrchestratorServiceServer will
// result in compilation errors.
type UnsafePaymentOrchestratorServiceServer interface {
	mustEmbedUnimplementedPaymentOrchestratorServiceServer()
}

func RegisterPaymentOrchestratorServiceServer(s grpc.ServiceRegistrar, srv PaymentOrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentOrchestratorService_ServiceDesc, srv)
}

func _PaymentOrchestratorService_ProposeFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ProposeFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ProposeFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ProposeFXAgreement(ctx, req.(*ProposeFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_AcceptFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).AcceptFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_AcceptFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).AcceptFXAgreement(ctx, req.(*AcceptFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RejectFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RejectFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RejectFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RejectFXAgreement(ctx, req.(*RejectFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_CancelFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).CancelFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_CancelFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).CancelFXAgreement(ctx, req.(*CancelFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_SettleFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).SettleFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_SettleFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).SettleFXAgreement(ctx, req.(*SettleFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetFXAgreement(ctx, req.(*GetFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ListFXAgreements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFXAgreementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ListFXAgreements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ListFXAgreements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ListFXAgreements(ctx, req.(*ListFXAgreementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ListFXAgreementEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFXAgreementEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ListFXAgreementEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ListFXAgreementEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ListFXAgreementEvents(ctx, req.(*ListFXAgreementEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_LockHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).LockHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_LockHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).LockHTLC(ctx, req.(*LockHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_LockHTLCWithHashLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockHTLCWithHashLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).LockHTLCWithHashLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_LockHTLCWithHashLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).LockHTLCWithHashLock(ctx, req.(*LockHTLCWithHashLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_SettleHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).SettleHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_SettleHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).SettleHTLC(ctx, req.(*SettleHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RefundHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RefundHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RefundHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RefundHTLC(ctx, req.(*RefundHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetHTLCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHTLCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetHTLCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetHTLCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetHTLCStatus(ctx, req.(*GetHTLCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_SearchHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).SearchHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_SearchHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).SearchHTLC(ctx, req.(*SearchHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetFiatBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFiatBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetFiatBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetFiatBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetFiatBalance(ctx, req.(*GetFiatBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RegisterDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RegisterDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RegisterDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RegisterDeposit(ctx, req.(*RegisterDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ApproveDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ApproveDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ApproveDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ApproveDeposit(ctx, req.(*ApproveDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RejectDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RejectDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RejectDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RejectDeposit(ctx, req.(*RejectDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RequestFiatExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFiatExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RequestFiatExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RequestFiatExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RequestFiatExchange(ctx, req.(*RequestFiatExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ListDeposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDepositsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ListDeposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ListDeposits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ListDeposits(ctx, req.(*ListDepositsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RequestEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RequestEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RequestEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RequestEscrow(ctx, req.(*RequestEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ApproveEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ApproveEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ApproveEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ApproveEscrow(ctx, req.(*ApproveEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RejectEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RejectEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RejectEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RejectEscrow(ctx, req.(*RejectEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ListEscrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEscrowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ListEscrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ListEscrows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ListEscrows(ctx, req.(*ListEscrowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RequestRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RequestRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RequestRedeem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RequestRedeem(ctx, req.(*RequestRedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ApproveRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ApproveRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ApproveRedeem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ApproveRedeem(ctx, req.(*ApproveRedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RejectRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RejectRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RejectRedeem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RejectRedeem(ctx, req.(*RejectRedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ListRedeems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRedeemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ListRedeems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ListRedeems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ListRedeems(ctx, req.(*ListRedeemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentOrchestratorService_ServiceDesc is the grpc.ServiceDesc for PaymentOrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentOrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_orchestrator.v1.PaymentOrchestratorService",
	HandlerType: (*PaymentOrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeFXAgreement",
			Handler:    _PaymentOrchestratorService_ProposeFXAgreement_Handler,
		},
		{
			MethodName: "AcceptFXAgreement",
			Handler:    _PaymentOrchestratorService_AcceptFXAgreement_Handler,
		},
		{
			MethodName: "RejectFXAgreement",
			Handler:    _PaymentOrchestratorService_RejectFXAgreement_Handler,
		},
		{
			MethodName: "CancelFXAgreement",
			Handler:    _PaymentOrchestratorService_CancelFXAgreement_Handler,
		},
		{
			MethodName: "SettleFXAgreement",
			Handler:    _PaymentOrchestratorService_SettleFXAgreement_Handler,
		},
		{
			MethodName: "GetFXAgreement",
			Handler:    _PaymentOrchestratorService_GetFXAgreement_Handler,
		},
		{
			MethodName: "ListFXAgreements",
			Handler:    _PaymentOrchestratorService_ListFXAgreements_Handler,
		},
		{
			MethodName: "ListFXAgreementEvents",
			Handler:    _PaymentOrchestratorService_ListFXAgreementEvents_Handler,
		},
		{
			MethodName: "LockHTLC",
			Handler:    _PaymentOrchestratorService_LockHTLC_Handler,
		},
		{
			MethodName: "LockHTLCWithHashLock",
			Handler:    _PaymentOrchestratorService_LockHTLCWithHashLock_Handler,
		},
		{
			MethodName: "SettleHTLC",
			Handler:    _PaymentOrchestratorService_SettleHTLC_Handler,
		},
		{
			MethodName: "RefundHTLC",
			Handler:    _PaymentOrchestratorService_RefundHTLC_Handler,
		},
		{
			MethodName: "GetHTLCStatus",
			Handler:    _PaymentOrchestratorService_GetHTLCStatus_Handler,
		},
		{
			MethodName: "SearchHTLC",
			Handler:    _PaymentOrchestratorService_SearchHTLC_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PaymentOrchestratorService_GetBalance_Handler,
		},
		{
			MethodName: "GetFiatBalance",
			Handler:    _PaymentOrchestratorService_GetFiatBalance_Handler,
		},
		{
			MethodName: "RegisterDeposit",
			Handler:    _PaymentOrchestratorService_RegisterDeposit_Handler,
		},
		{
			MethodName: "ApproveDeposit",
			Handler:    _PaymentOrchestratorService_ApproveDeposit_Handler,
		},
		{
			MethodName: "RejectDeposit",
			Handler:    _PaymentOrchestratorService_RejectDeposit_Handler,
		},
		{
			MethodName: "RequestFiatExchange",
			Handler:    _PaymentOrchestratorService_RequestFiatExchange_Handler,
		},
		{
			MethodName: "ListDeposits",
			Handler:    _PaymentOrchestratorService_ListDeposits_Handler,
		},
		{
			MethodName: "RequestEscrow",
			Handler:    _PaymentOrchestratorService_RequestEscrow_Handler,
		},
		{
			MethodName: "ApproveEscrow",
			Handler:    _PaymentOrchestratorService_ApproveEscrow_Handler,
		},
		{
			MethodName: "RejectEscrow",
			Handler:    _PaymentOrchestratorService_RejectEscrow_Handler,
		},
		{
			MethodName: "ListEscrows",
			Handler:    _PaymentOrchestratorService_ListEscrows_Handler,
		},
		{
			MethodName: "RequestRedeem",
			Handler:    _PaymentOrchestratorService_RequestRedeem_Handler,
		},
		{
			MethodName: "ApproveRedeem",
			Handler:    _PaymentOrchestratorService_ApproveRedeem_Handler,
		},
		{
			MethodName: "RejectRedeem",
			Handler:    _PaymentOrchestratorService_RejectRedeem_Handler,
		},
		{
			MethodName: "ListRedeems",
			Handler:    _PaymentOrchestratorService_ListRedeems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_orchestrator/v1/payment_orchestrator.proto",
}
