apiVersion: cbweb3/v1
kind: JoinBundle
metadata:
    name: spoke-brazil
    generatedAt: "2026-07-17T12:26:16Z"
spec:
    spokeId: spoke-brazil
    chainId: 2021
    currency: BRL
    bootnode:
        enode: enode://07e7c3a11a56bb4df63a7efa3223cacc0ae45bc7f7a860f369cf143a39d410fead2c9e5c016d485c8f87dcc0abc75fa825b0bf4cac759906847726a0604655ed@10.10.0.21:30303
        advertisedHost: 10.10.0.21
        p2pPort: 30303
    genesis:
        hash: sha256:697d5557327aca2471e7a66258a61382fc926e6575511a84ca5a28fa3a257d91
        content: ewogICJhbGxvYyIgOiB7CiAgICAiMTJlMjhmMTQ1MDAxY2UwNGNjYjI2Y2JjOTQ0YzI0NDYxM2Q0NzI3MCIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiMTdlMmZiNDZjM2M4NDQ1Y2Y0NThmZTk0Yjc5NWUzMmFlNTBmYWJhOSIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiMmQ1YmVjNjc2NDI3MWNkZGUwMmU2YTcyNzNhZTFlNjVkNTgxNTZhZiIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiM2ZjYjQ1ZTVmZWQwYzMzOWU2MjFiZjFjMmY4N2EzZDFmYjkyZTM5OSIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNjI3MzA2MDkwYWJhYjNhNmUxNDAwZTkzNDViYzYwYzc4YThiZWY1NyIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNzgzNGI1YWNmZDkxNzA2YjRkMTEwNDZhYzdmMjk2Y2EyZTk1MjhlYyIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiYTJlZjdmYWQzZmI3NzA1NDI0YjdjYzI3ZDIxNTI2ODI4ZGMwOGFlOCIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiYzExMDA4OTM4NWJhZDUwMjZlNTA4MzQ0M2MzYjQ0MzgwNmRhNDJkZiIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiYzVmZGY0MDc2YjhmM2E1MzU3YzVlMzk1YWI5NzBiNWI1NDA5OGZlZiIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiY2NiYTg0MWI0Y2E4MjRlNzI2MDk2MDlmNzlkZWU0M2E5OWU0NGI3NCIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiZjE3ZjUyMTUxZWJlZjZjNzMzNGZhZDA4MGM1NzA0ZDc3MjE2YjczMiIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiZmUzYjU1N2U4ZmI2MmI4OWY0OTE2YjcyMWJlNTVjZWI4MjhkYmQ3MyIgOiB7CiAgICAgICJiYWxhbmNlIiA6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJjb2luYmFzZSIgOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiY29uZmlnIiA6IHsKICAgICJiZXJsaW5CbG9jayIgOiAwLAogICAgImJ5emFudGl1bUJsb2NrIiA6IDAsCiAgICAiY2FuY3VuVGltZSIgOiAwLAogICAgImNoYWluSWQiIDogMjAyMSwKICAgICJjb25zdGFudGlub3BsZUJsb2NrIiA6IDAsCiAgICAiZWlwMTUwQmxvY2siIDogMCwKICAgICJlaXAxNTVCbG9jayIgOiAwLAogICAgImVpcDE1OEJsb2NrIiA6IDAsCiAgICAiaG9tZXN0ZWFkQmxvY2siIDogMCwKICAgICJpc3RhbmJ1bEJsb2NrIiA6IDAsCiAgICAibG9uZG9uQmxvY2siIDogMCwKICAgICJwZXRlcnNidXJnQmxvY2siIDogMCwKICAgICJwcmVNZXJnZUZvcmtCbG9jayIgOiAwLAogICAgInFiZnQiIDogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIiA6IDIsCiAgICAgICJlcG9jaGxlbmd0aCIgOiAzMDAwMCwKICAgICAgInJlcXVlc3R0aW1lb3V0c2Vjb25kcyIgOiA0CiAgICB9LAogICAgInNoYW5naGFpVGltZSIgOiAwLAogICAgInplcm9CYXNlRmVlIiA6IHRydWUKICB9LAogICJkaWZmaWN1bHR5IiA6ICIweDEiLAogICJnYXNMaW1pdCIgOiAiMHgxYzljMzgwIiwKICAibWl4SGFzaCIgOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAibm9uY2UiIDogIjB4MCIsCiAgInRpbWVzdGFtcCIgOiAiMHg1OGVlNDBiYSIsCiAgImV4dHJhRGF0YSIgOiAiMHhmODNhYTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZDU5NGU3OTYwNWYxNTlmYjc2MTIzMDc3ZDE4NWNhNjdkY2JhNzhjNTU3ZmFjMDgwYzAiCn0=
    contracts:
        registryAddress: 0x42699A7612A82f1d9C36148af9C77354759b210b
        zetoFactoryAddress: 0xfeae27388A65eE984F452f86efFEd42AaBD438FD
        penteFactoryAddress: 0xDE87AF9156a223404885002669D3bE239313Ae33
        zetoTokenAddress: 0x6213607c2fab2ddd572f7754a608565cd28ba7aa
        penteContextGroupId: ""
        penteContextAddress: ""
        fxAgreementAddress: ""
        participantRegistryAddress: 0x9ab7CA8a88F8e351f9b0eEEA5777929210199295
        fiatTokenAddress: 0x4245CF4518CB2C280f5e9c6a03c90C147F80B4d9
        htlcAddress: 0x5EB5888938e3fE7b334b1838B19C1e828c5148aA
    relay:
        endpoint: http://10.10.0.20:4000
    trust:
        caCertPEM: |
            -----BEGIN CERTIFICATE-----
            MIICIzCCAcmgAwIBAgIRALqngrSuKR9Ft5U8sHQ2lMwwCgYIKoZIzj0EAwIwTTEV
            MBMGA1UEChMMc3Bva2UtYnJhemlsMRowGAYDVQQLDBFST0xFX0NFTlRSQUxfQkFO
            SzEYMBYGA1UEAxMPc3Bva2UtYnJhemlsLWNiMB4XDTI2MDcxNzEyMjI0MloXDTM2
            MDcxNDEyMjM0MlowTTEVMBMGA1UEChMMc3Bva2UtYnJhemlsMRowGAYDVQQLDBFS
            T0xFX0NFTlRSQUxfQkFOSzEYMBYGA1UEAxMPc3Bva2UtYnJhemlsLWNiMFkwEwYH
            KoZIzj0CAQYIKoZIzj0DAQcDQgAEtlw/+51CFI0lRcaYBjVkRqXyANMiMsyze5Yv
            LA/elVdRHrYzVP0oqimFqe+Af6yhldj4FVS0xfpbf1CKvIn4XqOBiTCBhjAOBgNV
            HQ8BAf8EBAMCAoQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUsot5H8vbU3yt
            5FYN2ZTcQxk9icowRAYDVR0RBD0wO4IPc3Bva2UtYnJhemlsLWNighdwYWxhZGlu
            LXNwb2tlLWJyYXppbC1jYoIJbG9jYWxob3N0hwQKCgAVMAoGCCqGSM49BAMCA0gA
            MEUCIQDfqiva33KUCU21lyuKKC9FnsuIqzNX4NpyAOOFt33LHgIgcIEGAaMzJxsX
            eTdQPyyWdsIL/o4W9qXprFZod2/Ikj8=
            -----END CERTIFICATE-----
    validators:
        - address: 0xe79605F159FB76123077d185cA67dcBa78c557Fa
          rpcUrl: http://10.10.0.21:8645
    cbEndpoint: http://10.10.0.21:18645/api/v1/credential-request