package contract

import (
	"context"

	"google.golang.org/grpc"
)

const (
	ServiceName = "identity.v1.IdentityService"

	LoginMethod                = "/identity.v1.IdentityService/Login"
	RefreshTokenMethod         = "/identity.v1.IdentityService/RefreshToken"
	RevokeTokenMethod          = "/identity.v1.IdentityService/RevokeToken"
	ValidateTokenMethod        = "/identity.v1.IdentityService/ValidateToken"
	RegisterParticipantMethod  = "/identity.v1.IdentityService/RegisterParticipant"
	SignTransactionMethod      = "/identity.v1.IdentityService/SignTransaction"
	GetKYCStatusMethod         = "/identity.v1.IdentityService/GetKYCStatus"
	ProvisionParticipantMethod = "/identity.v1.IdentityService/ProvisionParticipant"
	OnboardParticipantMethod   = "/identity.v1.IdentityService/OnboardParticipant"
)

// --- Auth ---

type LoginRequest struct {
	User     string `json:"user"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token,omitempty"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int32  `json:"expires_in"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token,omitempty"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int32  `json:"expires_in"`
}

type RevokeTokenRequest struct {
	// AccessToken carries the token to revoke. In practice, callers should send
	// the refresh_token here, since Keycloak's logout endpoint requires a
	// refresh_token. This will be reconciled in a future iteration.
	AccessToken string `json:"access_token"`
}

type RevokeTokenResponse struct {
	Success bool `json:"success"`
}

// --- Token Validation ---

type ValidateTokenRequest struct {
	AccessToken string `json:"access_token"`
}

// ValidateTokenResponse carries enriched claims from the JWT (D7 §7.4).
type ValidateTokenResponse struct {
	Subject      string   `json:"subject"`
	Issuer       string   `json:"issuer"`
	Roles        []string `json:"roles"`
	DID          string   `json:"did,omitempty"`
	Wallet       string   `json:"wallet,omitempty"`
	Country      string   `json:"country,omitempty"`
	BankID       string   `json:"bank_id,omitempty"`
	PrivacyGroup string   `json:"privacy_group,omitempty"`
}

// --- Participant Registration ---

type RegisterParticipantRequest struct {
	AccessToken     string `json:"access_token"`
	Country         string `json:"country"`
	BankCode        string `json:"bank_code"`
	Role            string `json:"role"`
	InstitutionName string `json:"institution_name"`
}

type RegisterParticipantResponse struct {
	UserID        string `json:"user_id"`
	DID           string `json:"did"`
	WalletAddress string `json:"wallet_address"`
}

// --- Signing ---

type SignTransactionRequest struct {
	UserID string `json:"user_id"`
	Digest string `json:"digest"`
}

type SignTransactionResponse struct {
	UserID    string `json:"user_id"`
	Address   string `json:"address"`
	Signature string `json:"signature"`
}

// --- KYC Status ---

type GetKYCStatusRequest struct {
	Subject string `json:"subject"`
}

type GetKYCStatusResponse struct {
	Subject string `json:"subject"`
	Status  string `json:"status"`
}

type ProvisionParticipantRequest struct {
	Subject string `json:"subject"`
	Status  string `json:"status"` // PENDING, APPROVED, FROZEN, REVOKED
}

type ProvisionParticipantResponse struct {
	Subject string `json:"subject"`
	Status  string `json:"status"`
}

// --- Administrative Participant Onboarding ---

// OnboardParticipantRequest carries the data required for the Central Bank
// to register a new Commercial Bank or Treasury user (POST /compliance/register).
type OnboardParticipantRequest struct {
	// Username is the Keycloak username / login identifier for the new user.
	Username string `json:"username"`
	// Email is the email address of the new user (required by Keycloak).
	Email string `json:"email"`
	// Role is the prefixed role to assign (e.g. ROLE_COMMERCIAL_BANK, ROLE_TREASURY).
	Role string `json:"role"`
	// InstitutionName is the human-readable name of the bank or institution.
	InstitutionName string `json:"institution_name,omitempty"`
	// Country is the ISO-3166-1 alpha-2 country code.
	Country string `json:"country,omitempty"`
	// BankCode is an optional regulatory/internal bank identifier.
	BankCode string `json:"bank_code,omitempty"`
}

// OnboardParticipantResponse carries the result of a successful onboarding.
type OnboardParticipantResponse struct {
	// UserID is the Keycloak user UUID for the newly created user.
	UserID string `json:"user_id"`
	// WalletAddress is the EVM address generated by the KMS (only set for roles
	// that require KMS key generation, e.g. ROLE_COMMERCIAL_BANK).
	WalletAddress string `json:"wallet_address,omitempty"`
	// DID is the decentralized identifier derived from the wallet address.
	DID string `json:"did,omitempty"`
	// TxHash is the on-chain transaction hash from ParticipantRegistry.registerMember
	// (only set for roles that require on-chain registration).
	TxHash string `json:"tx_hash,omitempty"`
}

// --- Client Interface ---

// IdentityServiceClient is the typed client for all identity gRPC methods.
type IdentityServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	RegisterParticipant(ctx context.Context, in *RegisterParticipantRequest, opts ...grpc.CallOption) (*RegisterParticipantResponse, error)
	SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error)
	GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error)
	ProvisionParticipant(ctx context.Context, in *ProvisionParticipantRequest, opts ...grpc.CallOption) (*ProvisionParticipantResponse, error)
	OnboardParticipant(ctx context.Context, in *OnboardParticipantRequest, opts ...grpc.CallOption) (*OnboardParticipantResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc: cc}
}

func (c *identityServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	return out, c.cc.Invoke(ctx, LoginMethod, in, out, opts...)
}

func (c *identityServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	return out, c.cc.Invoke(ctx, RefreshTokenMethod, in, out, opts...)
}

func (c *identityServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	out := new(RevokeTokenResponse)
	return out, c.cc.Invoke(ctx, RevokeTokenMethod, in, out, opts...)
}

func (c *identityServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	return out, c.cc.Invoke(ctx, ValidateTokenMethod, in, out, opts...)
}

func (c *identityServiceClient) RegisterParticipant(ctx context.Context, in *RegisterParticipantRequest, opts ...grpc.CallOption) (*RegisterParticipantResponse, error) {
	out := new(RegisterParticipantResponse)
	return out, c.cc.Invoke(ctx, RegisterParticipantMethod, in, out, opts...)
}

func (c *identityServiceClient) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error) {
	out := new(SignTransactionResponse)
	return out, c.cc.Invoke(ctx, SignTransactionMethod, in, out, opts...)
}

func (c *identityServiceClient) GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error) {
	out := new(GetKYCStatusResponse)
	return out, c.cc.Invoke(ctx, GetKYCStatusMethod, in, out, opts...)
}

func (c *identityServiceClient) ProvisionParticipant(ctx context.Context, in *ProvisionParticipantRequest, opts ...grpc.CallOption) (*ProvisionParticipantResponse, error) {
	out := new(ProvisionParticipantResponse)
	return out, c.cc.Invoke(ctx, ProvisionParticipantMethod, in, out, opts...)
}

func (c *identityServiceClient) OnboardParticipant(ctx context.Context, in *OnboardParticipantRequest, opts ...grpc.CallOption) (*OnboardParticipantResponse, error) {
	out := new(OnboardParticipantResponse)
	return out, c.cc.Invoke(ctx, OnboardParticipantMethod, in, out, opts...)
}
