PKI_DIR := backend/config/pki
OPENSSL  := openssl
COMMERCIAL_BANK_IDS := bank-a bank-b bank-c bank-d
COMMERCIAL_BANK_GEN_TARGETS := $(addprefix pki.gen-commercial-bank-,$(COMMERCIAL_BANK_IDS))

# Guard: skip generation if .key already exists, unless FORCE=1 is set
define gen_ca
	@if [ -f "$(1)" ] && [ "$(FORCE)" != "1" ]; then \
		echo "  [skip] $(1) already exists (run with FORCE=1 to regenerate)"; \
	else \
		echo "  Generating $(2) private key..."; \
		$(OPENSSL) ecparam -genkey -name prime256v1 -noout -out "$(1)"; \
		echo "  Generating $(2) self-signed certificate..."; \
		$(OPENSSL) req -new -x509 \
			-key "$(1)" \
			-out "$(3)" \
			-days 3650 \
			-subj "$(4)"; \
		echo "  Done: $(3)"; \
	fi
endef

# ===========================================================================
# [DEV ONLY] LOCAL DEVELOPMENT BOOTSTRAP — NOT the production PKI flow.
#
# This macro generates a per-bank self-signed CA (bank-x-ca.key/crt) and
# uses it to sign the bank's own leaf certificate. This is a LOCAL SHORTCUT
# that lets developers spin up the stack without a running Central Bank.
#
# PRODUCTION FLOW (correct model, already implemented):
#   1. Commercial bank generates keypair + CSR (OU=ROLE_COMMERCIAL_BANK).
#   2. Bank submits CSR to Central Bank via:
#        POST /api/v1/onboarding/credential-request
#   3. Central Bank signs the CSR with its spoke CA (central-bank-x-ca.key).
#   4. Bank receives a leaf cert issued by the CB CA — never a bank-owned CA.
#
# Reference implementation: scenario-a/backend/services/api-gateway/internal/
#   http/handlers/onboarding_proxy.go (smart mode — InitiateCredentialRequest)
# PKI library: scenario-a/backend/shared/identity/ca.go (GenerateCSR, SignCSR)
# ===========================================================================
# Guard: skip generation if participant certificate already exists, unless FORCE=1.
# Reuses existing entity CA if present (generated by pki.gen-bank-*).
define gen_commercial_bank_cert
	@bank="$(1)"; \
	ca_key="$(PKI_DIR)/$$bank-ca.key"; \
	ca_crt="$(PKI_DIR)/$$bank-ca.crt"; \
	participant_key="$(PKI_DIR)/$$bank.key"; \
	participant_csr="$(PKI_DIR)/$$bank.csr"; \
	participant_crt="$(PKI_DIR)/$$bank.crt"; \
	serial_hex="$$(openssl rand -hex 8)"; \
	if [ -f "$$participant_crt" ] && [ "$(FORCE)" != "1" ]; then \
		echo "  [skip] $$participant_crt already exists (run with FORCE=1 to regenerate)"; \
	else \
		if [ -f "$$ca_key" ] && [ -f "$$ca_crt" ]; then \
			echo "  Reusing existing $$bank CA..."; \
		else \
			echo "  Generating $$bank CA private key..."; \
			$(OPENSSL) ecparam -genkey -name prime256v1 -noout -out "$$ca_key"; \
			echo "  Generating $$bank CA certificate..."; \
			$(OPENSSL) req -new -x509 \
				-key "$$ca_key" \
				-out "$$ca_crt" \
				-days 3650 \
				-subj "/CN=$$bank-CA/O=$$bank/C=BR"; \
		fi; \
		echo "  Generating $$bank participant private key..."; \
		$(OPENSSL) ecparam -genkey -name prime256v1 -noout -out "$$participant_key"; \
		echo "  Generating $$bank participant CSR..."; \
		$(OPENSSL) req -new \
			-key "$$participant_key" \
			-out "$$participant_csr" \
			-subj "/CN=$$bank/O=$$bank/OU=ROLE_COMMERCIAL_BANK/C=BR"; \
		echo "  Signing $$bank participant certificate with $$bank CA..."; \
		$(OPENSSL) x509 -req \
			-in "$$participant_csr" \
			-CA "$$ca_crt" \
			-CAkey "$$ca_key" \
			-set_serial "0x$$serial_hex" \
			-out "$$participant_crt" \
			-days 1825 \
			-sha256; \
		echo "  Done: $$participant_crt"; \
	fi
endef

pki.gen-central-bank-a:
	@echo "==> Central-Bank-A CA (spoke-a)"
	$(call gen_ca,$(PKI_DIR)/central-bank-a-ca.key,CentralBankA,$(PKI_DIR)/central-bank-a-ca.crt,/CN=CBWeb3-CentralBankA-CA/O=CentralBankA/C=BR)

pki.gen-central-bank-b:
	@echo "==> Central-Bank-B CA (spoke-b)"
	$(call gen_ca,$(PKI_DIR)/central-bank-b-ca.key,CentralBankB,$(PKI_DIR)/central-bank-b-ca.crt,/CN=CBWeb3-CentralBankB-CA/O=CentralBankB/C=BR)

# [DEV ONLY] pki.gen-bank-* — generates a self-signed CA per commercial bank for local dev bootstrap.
# In production, commercial banks MUST NOT hold their own CA; they receive a leaf cert
# signed by the Central Bank via the CSR->CB flow (POST /api/v1/onboarding/credential-request).
pki.gen-bank-a:
	@echo "==> Bank-A CA (spoke-a) [DEV ONLY — local bootstrap, does not represent production]"
	$(call gen_ca,$(PKI_DIR)/bank-a-ca.key,BankA,$(PKI_DIR)/bank-a-ca.crt,/CN=CBWeb3-BankA-CA/O=BankA/C=BR)

pki.gen-bank-b:
	@echo "==> Bank-B CA (spoke-b) [DEV ONLY — local bootstrap, does not represent production]"
	$(call gen_ca,$(PKI_DIR)/bank-b-ca.key,BankB,$(PKI_DIR)/bank-b-ca.crt,/CN=CBWeb3-BankB-CA/O=BankB/C=BR)

pki.gen-bank-c:
	@echo "==> Bank-C CA (spoke-a) [DEV ONLY — local bootstrap, does not represent production]"
	$(call gen_ca,$(PKI_DIR)/bank-c-ca.key,BankC,$(PKI_DIR)/bank-c-ca.crt,/CN=CBWeb3-BankC-CA/O=BankC/C=BR)

pki.gen-bank-d:
	@echo "==> Bank-D CA (spoke-b) [DEV ONLY — local bootstrap, does not represent production]"
	$(call gen_ca,$(PKI_DIR)/bank-d-ca.key,BankD,$(PKI_DIR)/bank-d-ca.crt,/CN=CBWeb3-BankD-CA/O=BankD/C=BR)

pki.gen-all: pki.gen-central-bank-a pki.gen-central-bank-b pki.gen-bank-a pki.gen-bank-b pki.gen-bank-c pki.gen-bank-d pki.gen-commercial-banks
	@echo "==> All PKI credentials generated in $(PKI_DIR)/"

pki.gen-commercial-bank-%:
	@echo "==> Commercial Bank PKI: $*"
	@echo "  [DEV ONLY] Local bootstrap: bank generates its own self-signed CA."
	@echo "  [DEV ONLY] In production, the bank sends a CSR to the Central Bank for signing via"
	@echo "  [DEV ONLY] POST /api/v1/onboarding/credential-request (onboarding_proxy.go)."
	$(call gen_commercial_bank_cert,$*)

pki.gen-commercial-banks: $(COMMERCIAL_BANK_GEN_TARGETS)
	@echo "==> Commercial bank certificates generated in $(PKI_DIR)/"

pki.check: pki.check-commercial-banks
	@echo "==> PKI certificate status ($(PKI_DIR)/):"
	@for f in central-bank-a-ca.key central-bank-a-ca.crt central-bank-b-ca.key central-bank-b-ca.crt bank-a-ca.key bank-a-ca.crt bank-b-ca.key bank-b-ca.crt bank-c-ca.key bank-c-ca.crt bank-d-ca.key bank-d-ca.crt; do \
		if [ -f "$(PKI_DIR)/$$f" ]; then \
			echo "  [OK]     $$f"; \
		else \
			echo "  [MISSING] $$f"; \
		fi; \
	done

pki.check-commercial-banks:
	@echo "==> Commercial bank PKI status ($(PKI_DIR)/):"
	@for bank in $(COMMERCIAL_BANK_IDS); do \
		for suffix in -ca.key -ca.crt .key .csr .crt; do \
			f="$$bank$$suffix"; \
			if [ -f "$(PKI_DIR)/$$f" ]; then \
				echo "  [OK]      $$f"; \
			else \
				echo "  [MISSING] $$f"; \
			fi; \
		done; \
	done

pki.clean:
	@echo "==> Removing CA credentials from $(PKI_DIR)/"
	@rm -f $(PKI_DIR)/central-bank-a-ca.key $(PKI_DIR)/central-bank-a-ca.crt
	@rm -f $(PKI_DIR)/central-bank-b-ca.key $(PKI_DIR)/central-bank-b-ca.crt
	@rm -f $(PKI_DIR)/bank-a-ca.key $(PKI_DIR)/bank-a-ca.crt
	@rm -f $(PKI_DIR)/bank-b-ca.key $(PKI_DIR)/bank-b-ca.crt
	@rm -f $(PKI_DIR)/bank-c-ca.key $(PKI_DIR)/bank-c-ca.crt
	@rm -f $(PKI_DIR)/bank-d-ca.key $(PKI_DIR)/bank-d-ca.crt
	@echo "  Done."

pki.clean-commercial-banks:
	@echo "==> Removing commercial bank credentials from $(PKI_DIR)/"
	@rm -f $(foreach bank,$(COMMERCIAL_BANK_IDS),$(PKI_DIR)/$(bank)-ca.key $(PKI_DIR)/$(bank)-ca.crt $(PKI_DIR)/$(bank)-ca.srl $(PKI_DIR)/$(bank).key $(PKI_DIR)/$(bank).csr $(PKI_DIR)/$(bank).crt)
	@echo "  Done."

.PHONY: pki.gen-central-bank-a pki.gen-central-bank-b pki.gen-bank-a pki.gen-bank-b pki.gen-bank-c pki.gen-bank-d pki.gen-all pki.check pki.clean pki.gen-commercial-banks pki.check-commercial-banks pki.clean-commercial-banks
