#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
CI gate: every secret / hash-lock pair the Toolbox documents must recompute correctly.

WHY THIS EXISTS
---------------
Every Toolbox artifact before the 2026-08 realignment claimed that

    SHA-256("cbweb3-test-secret-2026") = 0x7f83b165...9069

and instructed implementers to verify it. The claim was false twice over: the digest of
that string is 000cd63c...fdcf, and the string is not valid hex, so a gateway would have
rejected it outright. The value 7f83b165... could not be identified as the digest of any
obvious candidate. Anyone who followed the Toolbox's own instruction got a mismatch, and
nothing in CI noticed for four sessions.

A cryptographic reference value that is not recomputed is not a reference value. This gate
recomputes every pair the repository publishes.

THE DERIVATION, WHICH IS EASY TO GET WRONG
------------------------------------------
The CBWeb3 gateway carries the HTLC secret as **64 lowercase hex characters (32 bytes)** and
hashes the **decoded bytes**:

    hash_lock = SHA-256(hex_decode(secret))

It does NOT hash the ASCII of the string you send. A human-readable passphrase is not a
valid secret. This tool checks the hex-decoded derivation first and, when a secret is not
valid hex, falls back to the ASCII derivation so that a documented pair using the older
convention is still verified rather than silently skipped — but it reports the fallback,
because a non-hex secret would be rejected by a real gateway.

WHERE PAIRS COME FROM
---------------------
1. `syntheticSecrets` blocks in `Toolbox/test-vectors/*/*.json`, pairing keys by name
   (`secretHex`/`hashLock`, `wrongSecretHex`/`wrongSecretHash`, `secret`/`hash`, ...).
2. `Toolbox/mocks/**/*.json`, grouped by `contract_id`: when one fixture reveals a
   `secret` for a contract and another carries its `hash_lock`, the pair is verified across
   files. This is the check that matters most, because it is the settle fixture an
   integrator copies.
3. `HTLC_SECRET` / `HTLC_HASHLOCK` in `Toolbox/sandbox/sample-configs/.env.example`.
4. Markdown reference tables and verification one-liners in `Toolbox/**/*.md`.

A hash lock with no published secret is reported for information and is NOT a failure: a
real lock's secret is generated by the gateway and stays private until settlement, so a
fixture for an unsettled or refunded lock legitimately publishes only the digest.

Exit status: 0 if every documented pair recomputes, 1 otherwise.
"""

from __future__ import annotations

import glob
import hashlib
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TOOLBOX = os.path.join(REPO_ROOT, "Toolbox")

HEX64 = re.compile(r"^[0-9a-f]{64}$")

# Discredited value that must never come back as a usable digest.
RETRACTED_PREFIX = "7f83b1" + "65"


def rel(path: str) -> str:
    return os.path.relpath(path, REPO_ROOT)


def normalise(value: str) -> str:
    return value.strip().lower().removeprefix("0x")


def derive(secret: str) -> list[tuple[str, str]]:
    """Return [(derivation-name, digest)] candidates for a documented secret."""
    candidates: list[tuple[str, str]] = []
    cleaned = normalise(secret)
    if HEX64.match(cleaned):
        candidates.append(
            ("SHA-256(hex_decode(secret))", hashlib.sha256(bytes.fromhex(cleaned)).hexdigest())
        )
    candidates.append(("SHA-256(ascii(secret))", hashlib.sha256(secret.encode()).hexdigest()))
    return candidates


class Checker:
    def __init__(self) -> None:
        self.pairs: list[tuple[str, str, str, str]] = []  # (source, label, secret, hash)
        self.orphans: list[tuple[str, str]] = []          # (source, hash with no secret)
        self.declared: set[str] = set()                   # digests declared secretWithheld
        self.errors: list[str] = []                       # gate defects, not pair mismatches

    def add(self, source: str, label: str, secret: str, digest: str) -> None:
        self.pairs.append((source, label, secret, normalise(digest)))

    # -- source 1: vector syntheticSecrets ---------------------------------
    def scan_vectors(self) -> None:
        for path in sorted(glob.glob(os.path.join(TOOLBOX, "test-vectors", "*", "*.json"))):
            with open(path, encoding="utf-8") as handle:
                doc = json.load(handle)
            block = doc.get("syntheticSecrets")
            if not isinstance(block, dict):
                continue
            # Pair "<prefix>secret[hex]" with "<prefix>hash[lock]" on a shared prefix.
            secrets: dict[str, str] = {}
            hashes: dict[str, str] = {}
            for key, value in block.items():
                if not isinstance(value, str):
                    continue
                low = key.lower()
                # "hash" wins over "secret": `wrongSecretHash` is a digest, not a secret.
                if "hash" in low:
                    prefix = (low.replace("hashlock", "").replace("hash", "")
                                 .replace("secret", "").replace("hex", ""))
                    if prefix in hashes and hashes[prefix] != value:
                        self.errors.append(
                            f"{rel(path)}: syntheticSecrets keys collide on prefix "
                            f"'{prefix or 'default'}' — {hashes[prefix][:16]}… and "
                            f"{value[:16]}… cannot both be checked. Rename one key.")
                    hashes[prefix] = value
                elif "secret" in low:
                    prefix = low.replace("secret", "").replace("hex", "")
                    if prefix in secrets and secrets[prefix] != value:
                        self.errors.append(
                            f"{rel(path)}: syntheticSecrets keys collide on prefix "
                            f"'{prefix or 'default'}' — two secrets map to it. Rename one key.")
                    secrets[prefix] = value
            for prefix, secret in secrets.items():
                if prefix in hashes:
                    self.add(rel(path), f"syntheticSecrets[{prefix or 'default'}]",
                             secret, hashes[prefix])

    # -- source 2: mocks, grouped by contract_id ---------------------------
    def scan_mocks(self) -> None:
        secrets: dict[str, tuple[str, str]] = {}   # contract_id -> (secret, source)
        locks: dict[str, list[tuple[str, str]]] = {}  # contract_id -> [(hash, source)]

        def walk(node, found: dict) -> None:
            if isinstance(node, dict):
                for key, value in node.items():
                    if isinstance(value, str):
                        if key == "contract_id":
                            found.setdefault("contract_id", value)
                        elif key == "secret" and value:
                            found.setdefault("secret", value)
                        elif key in ("hash_lock", "hashLock") and value:
                            found.setdefault("hash_lock", value)
                    walk(value, found)
            elif isinstance(node, list):
                for item in node:
                    walk(item, found)

        for path in sorted(glob.glob(os.path.join(TOOLBOX, "mocks", "**", "*.json"),
                                     recursive=True)):
            with open(path, encoding="utf-8") as handle:
                doc = json.load(handle)
            found: dict = {}
            walk(doc, found)
            cid = found.get("contract_id")
            if not cid:
                continue
            if found.get("secret"):
                secrets.setdefault(cid, (found["secret"], rel(path)))
            if found.get("hash_lock"):
                locks.setdefault(cid, []).append((found["hash_lock"], rel(path)))
                # A fixture may declare that no preimage exists for this digest, and why.
                if isinstance(doc.get("secretWithheld"), str) and doc["secretWithheld"].strip():
                    self.declared.add(normalise(found["hash_lock"]))

        for cid, entries in locks.items():
            if cid in secrets:
                secret, secret_source = secrets[cid]
                for digest, lock_source in entries:
                    self.add(
                        f"{lock_source} (secret from {secret_source})",
                        f"contract_id {cid[:16]}…",
                        secret,
                        digest,
                    )
            else:
                for digest, lock_source in entries:
                    self.orphans.append((lock_source, normalise(digest)))

    # -- source 3: .env.example -------------------------------------------
    def scan_env(self) -> None:
        path = os.path.join(TOOLBOX, "sandbox", "sample-configs", ".env.example")
        if not os.path.exists(path):
            return
        values: dict[str, str] = {}
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
        if "HTLC_SECRET" in values and "HTLC_HASHLOCK" in values:
            self.add(rel(path), "HTLC_SECRET / HTLC_HASHLOCK",
                     values["HTLC_SECRET"], values["HTLC_HASHLOCK"])

    # -- source 4: markdown ------------------------------------------------
    def scan_markdown(self) -> None:
        # (a) printf '<secret>' | xxd -r -p | sha256sum   followed by   # <digest>
        shell = re.compile(
            r"printf\s+'([^']+)'\s*\|\s*xxd\s+-r\s+-p\s*\|\s*sha256sum\s*\n\s*#\s*([0-9a-f]{64})"
        )
        # (b) printf '<secret>' | sha256sum               followed by   # <digest>
        shell_ascii = re.compile(
            r"printf\s+'([^']+)'\s*\|\s*sha256sum\s*\n\s*#\s*([0-9a-f]{64})"
        )
        # (c) a reference table: | Secret ... | `x` |  ... | Hash lock | `y` |
        table_secret = re.compile(r"^\|\s*Secret[^|]*\|\s*`([^`]+)`\s*\|", re.M)
        table_hash = re.compile(r"^\|\s*Hash ?lock[^|]*\|\s*`([0-9a-fx]{64,66})`\s*\|", re.M | re.I)

        for path in sorted(glob.glob(os.path.join(TOOLBOX, "**", "*.md"), recursive=True)):
            raw = open(path, encoding="utf-8").read()
            # Verification one-liners are often inside a blockquote callout. Strip the
            # quote markers so a `> printf ... | sha256sum` block is still checked.
            text = re.sub(r"^\s*>\s?", "", raw, flags=re.M)
            for pattern, label in ((shell, "printf | xxd | sha256sum"),
                                   (shell_ascii, "printf | sha256sum")):
                for secret, digest in pattern.findall(text):
                    self.add(rel(path), label, secret, digest)
            secrets = table_secret.findall(text)
            hashes = table_hash.findall(text)
            if len(secrets) != len(hashes):
                self.errors.append(
                    f"{rel(path)}: {len(secrets)} table secret row(s) but {len(hashes)} "
                    "hash-lock row(s) — they cannot be paired, so none was checked.")
            else:
                for index, (secret, digest) in enumerate(zip(secrets, hashes)):
                    label = ("reference-value table" if len(secrets) == 1
                             else f"reference-value table[{index}]")
                    self.add(rel(path), label, secret, digest)

    # -- rule 2: the retracted digest must not appear as a hash-bearing VALUE
    def scan_retracted_values(self) -> list[str]:
        """
        A grep cannot tell `"hash_lock": "0x7f83b165..."` from a sentence explaining why
        that value was withdrawn. This can: it walks the parsed artifacts and only looks at
        values of hash-bearing fields.

        Prose is therefore free to record the history — the Toolbox's provenance notes
        depend on being able to name the value they retract — while no fixture, contract or
        example may carry it.
        """
        hits: list[str] = []
        hash_keys = ("hash_lock", "hashlock", "hash", "secret", "example", "default")

        def walk(node, source: str, key_path: str) -> None:
            if isinstance(node, dict):
                for key, value in node.items():
                    walk(value, source, f"{key_path}.{key}" if key_path else str(key))
            elif isinstance(node, list):
                for index, item in enumerate(node):
                    walk(item, source, f"{key_path}[{index}]")
            elif isinstance(node, str):
                leaf = key_path.rsplit(".", 1)[-1].split("[")[0].lower()
                if leaf in hash_keys and RETRACTED_PREFIX in normalise(node):
                    hits.append(f"{source}: {key_path} carries the discredited digest")

        targets = (
            glob.glob(os.path.join(TOOLBOX, "mocks", "**", "*.json"), recursive=True)
            + glob.glob(os.path.join(TOOLBOX, "test-vectors", "*", "*.json"))
        )
        for path in sorted(targets):
            try:
                with open(path, encoding="utf-8") as handle:
                    walk(json.load(handle), rel(path), "")
            except json.JSONDecodeError:
                continue  # the schema gate reports malformed JSON

        # Contracts are YAML; a plain substring scan of their examples is enough, because a
        # contract has no reason to discuss the Toolbox's own history.
        for path in sorted(glob.glob(os.path.join(TOOLBOX, "contracts", "*", "openapi_*.yaml"))):
            text = open(path, encoding="utf-8").read().lower()
            if RETRACTED_PREFIX in text:
                hits.append(f"{rel(path)}: contains the discredited digest")
        return hits

    # -- run ---------------------------------------------------------------
    def run(self) -> int:
        self.scan_vectors()
        self.scan_mocks()
        self.scan_env()
        self.scan_markdown()

        if not self.pairs:
            print("No documented secret / hash-lock pairs were found.")
            print("That is itself suspicious — this gate exists because the Toolbox "
                  "publishes verifiable reference values.")
            return 1

        failures: list[str] = list(self.scan_retracted_values())
        fallbacks: list[str] = []
        verified_digests: set[str] = set()

        for source, label, secret, expected in sorted(set(self.pairs)):
            if expected.startswith(RETRACTED_PREFIX):
                failures.append(
                    f"{source}: {label} publishes the discredited hash lock. "
                    "It is not the SHA-256 of anything."
                )
                continue
            candidates = derive(secret)
            match = next((name for name, digest in candidates if digest == expected), None)
            if match is None:
                shown = "\n".join(f"          {name} = {digest}" for name, digest in candidates)
                failures.append(
                    f"{source}: {label} does not recompute.\n"
                    f"          secret   = {secret}\n"
                    f"          claimed  = {expected}\n{shown}"
                )
                continue
            if match.startswith("SHA-256(ascii"):
                fallbacks.append(
                    f"{source}: {label} verifies only as SHA-256 of the ASCII string. "
                    "The gateway hex-decodes the secret, so a real gateway would reject it."
                )
            verified_digests.add(expected)
            print(f"  OK  {source}: {label} — {match}")

        print(f"\nVerified {len(set(self.pairs))} documented secret / hash-lock pair(s).")

        remaining = [(source, digest) for source, digest in sorted(set(self.orphans))
                     if digest not in verified_digests]
        shared = [(source, digest) for source, digest in sorted(set(self.orphans))
                  if digest in verified_digests]
        if shared:
            print(f"\n{len(shared)} hash lock(s) reuse a digest verified above — which is "
                  "exactly right:\nboth legs of an HTLC swap share one hash lock.")
            for source, digest in shared:
                print(f"  OK  {source}: {digest[:16]}…")
        undeclared = [(source, digest) for source, digest in remaining
                      if digest not in self.declared]
        declared = [(source, digest) for source, digest in remaining
                    if digest in self.declared]
        if declared:
            print(f"\n{len(declared)} hash lock(s) published without a secret, each "
                  "declaring why via secretWithheld:")
            for source, digest in declared:
                print(f"  OK  {source}: {digest[:16]}…")
        if undeclared:
            self.errors.append(
                f"{len(undeclared)} hash lock(s) published with no documented secret and no "
                "secretWithheld declaration:\n" +
                "\n".join(f"      {source}: {digest[:16]}…" for source, digest in undeclared) +
                "\n    An undeclared orphan is indistinguishable from an unrecomputable "
                "published digest.\n    Add a secretWithheld note saying why the preimage "
                "is absent, or publish the secret.")

        if fallbacks:
            print("\nWARNING — non-hex secrets:")
            for note in fallbacks:
                print(f"  !!  {note}")

        if self.errors:
            print(f"\n{len(self.errors)} gate defect(s) — the check could not do its job:\n")
            for error in self.errors:
                print(f"  !!  {error}")

        if failures:
            print(f"\n{len(failures)} documented pair(s) FAILED to recompute:\n")
            for failure in failures:
                print(f"  - {failure}")
            print(
                "\nA cryptographic reference value that does not recompute is worse than "
                "no reference value:\nan integrator who trusts it gets a mismatch and "
                "blames their own implementation."
            )
            return 1

        if self.errors:
            return 1

        print("\nOK — every documented secret / hash-lock pair recomputes correctly.")
        return 0


if __name__ == "__main__":
    sys.exit(Checker().run())
