// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: compliance/v1/compliance.proto

package compliancv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComplianceService_UpsertParticipant_FullMethodName           = "/compliance.v1.ComplianceService/UpsertParticipant"
	ComplianceService_GetParticipantByUser_FullMethodName        = "/compliance.v1.ComplianceService/GetParticipantByUser"
	ComplianceService_ListParticipants_FullMethodName            = "/compliance.v1.ComplianceService/ListParticipants"
	ComplianceService_CreateAuditLog_FullMethodName              = "/compliance.v1.ComplianceService/CreateAuditLog"
	ComplianceService_GetAuditLogs_FullMethodName                = "/compliance.v1.ComplianceService/GetAuditLogs"
	ComplianceService_IssueParticipantCertificate_FullMethodName = "/compliance.v1.ComplianceService/IssueParticipantCertificate"
	ComplianceService_SignParticipantCSR_FullMethodName          = "/compliance.v1.ComplianceService/SignParticipantCSR"
	ComplianceService_ApproveKYC_FullMethodName                  = "/compliance.v1.ComplianceService/ApproveKYC"
	ComplianceService_ManageParticipantStatus_FullMethodName     = "/compliance.v1.ComplianceService/ManageParticipantStatus"
	ComplianceService_GetCircuitBreakerStatus_FullMethodName     = "/compliance.v1.ComplianceService/GetCircuitBreakerStatus"
	ComplianceService_ToggleCircuitBreaker_FullMethodName        = "/compliance.v1.ComplianceService/ToggleCircuitBreaker"
	ComplianceService_GetSystemParameters_FullMethodName         = "/compliance.v1.ComplianceService/GetSystemParameters"
	ComplianceService_UpdateSystemParameters_FullMethodName      = "/compliance.v1.ComplianceService/UpdateSystemParameters"
)

// ComplianceServiceClient is the client API for ComplianceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComplianceServiceClient interface {
	UpsertParticipant(ctx context.Context, in *UpsertParticipantRequest, opts ...grpc.CallOption) (*UpsertParticipantResponse, error)
	GetParticipantByUser(ctx context.Context, in *GetParticipantByUserRequest, opts ...grpc.CallOption) (*GetParticipantByUserResponse, error)
	ListParticipants(ctx context.Context, in *ListParticipantsRequest, opts ...grpc.CallOption) (*ListParticipantsResponse, error)
	CreateAuditLog(ctx context.Context, in *CreateAuditLogRequest, opts ...grpc.CallOption) (*CreateAuditLogResponse, error)
	GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
	IssueParticipantCertificate(ctx context.Context, in *IssueParticipantCertificateRequest, opts ...grpc.CallOption) (*IssueParticipantCertificateResponse, error)
	SignParticipantCSR(ctx context.Context, in *SignParticipantCSRRequest, opts ...grpc.CallOption) (*SignParticipantCSRResponse, error)
	ApproveKYC(ctx context.Context, in *ApproveKYCRequest, opts ...grpc.CallOption) (*ApproveKYCResponse, error)
	ManageParticipantStatus(ctx context.Context, in *ManageParticipantStatusRequest, opts ...grpc.CallOption) (*ManageParticipantStatusResponse, error)
	GetCircuitBreakerStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCircuitBreakerStatusResponse, error)
	ToggleCircuitBreaker(ctx context.Context, in *ToggleCircuitBreakerRequest, opts ...grpc.CallOption) (*ToggleCircuitBreakerResponse, error)
	GetSystemParameters(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSystemParametersResponse, error)
	UpdateSystemParameters(ctx context.Context, in *UpdateSystemParametersRequest, opts ...grpc.CallOption) (*UpdateSystemParametersResponse, error)
}

type complianceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComplianceServiceClient(cc grpc.ClientConnInterface) ComplianceServiceClient {
	return &complianceServiceClient{cc}
}

func (c *complianceServiceClient) UpsertParticipant(ctx context.Context, in *UpsertParticipantRequest, opts ...grpc.CallOption) (*UpsertParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertParticipantResponse)
	err := c.cc.Invoke(ctx, ComplianceService_UpsertParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) GetParticipantByUser(ctx context.Context, in *GetParticipantByUserRequest, opts ...grpc.CallOption) (*GetParticipantByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParticipantByUserResponse)
	err := c.cc.Invoke(ctx, ComplianceService_GetParticipantByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) ListParticipants(ctx context.Context, in *ListParticipantsRequest, opts ...grpc.CallOption) (*ListParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParticipantsResponse)
	err := c.cc.Invoke(ctx, ComplianceService_ListParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) CreateAuditLog(ctx context.Context, in *CreateAuditLogRequest, opts ...grpc.CallOption) (*CreateAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuditLogResponse)
	err := c.cc.Invoke(ctx, ComplianceService_CreateAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, ComplianceService_GetAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) IssueParticipantCertificate(ctx context.Context, in *IssueParticipantCertificateRequest, opts ...grpc.CallOption) (*IssueParticipantCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueParticipantCertificateResponse)
	err := c.cc.Invoke(ctx, ComplianceService_IssueParticipantCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) SignParticipantCSR(ctx context.Context, in *SignParticipantCSRRequest, opts ...grpc.CallOption) (*SignParticipantCSRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignParticipantCSRResponse)
	err := c.cc.Invoke(ctx, ComplianceService_SignParticipantCSR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) ApproveKYC(ctx context.Context, in *ApproveKYCRequest, opts ...grpc.CallOption) (*ApproveKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveKYCResponse)
	err := c.cc.Invoke(ctx, ComplianceService_ApproveKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) ManageParticipantStatus(ctx context.Context, in *ManageParticipantStatusRequest, opts ...grpc.CallOption) (*ManageParticipantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageParticipantStatusResponse)
	err := c.cc.Invoke(ctx, ComplianceService_ManageParticipantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) GetCircuitBreakerStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCircuitBreakerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCircuitBreakerStatusResponse)
	err := c.cc.Invoke(ctx, ComplianceService_GetCircuitBreakerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) ToggleCircuitBreaker(ctx context.Context, in *ToggleCircuitBreakerRequest, opts ...grpc.CallOption) (*ToggleCircuitBreakerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleCircuitBreakerResponse)
	err := c.cc.Invoke(ctx, ComplianceService_ToggleCircuitBreaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) GetSystemParameters(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSystemParametersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemParametersResponse)
	err := c.cc.Invoke(ctx, ComplianceService_GetSystemParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) UpdateSystemParameters(ctx context.Context, in *UpdateSystemParametersRequest, opts ...grpc.CallOption) (*UpdateSystemParametersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSystemParametersResponse)
	err := c.cc.Invoke(ctx, ComplianceService_UpdateSystemParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplianceServiceServer is the server API for ComplianceService service.
// All implementations should embed UnimplementedComplianceServiceServer
// for forward compatibility.
type ComplianceServiceServer interface {
	UpsertParticipant(context.Context, *UpsertParticipantRequest) (*UpsertParticipantResponse, error)
	GetParticipantByUser(context.Context, *GetParticipantByUserRequest) (*GetParticipantByUserResponse, error)
	ListParticipants(context.Context, *ListParticipantsRequest) (*ListParticipantsResponse, error)
	CreateAuditLog(context.Context, *CreateAuditLogRequest) (*CreateAuditLogResponse, error)
	GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error)
	IssueParticipantCertificate(context.Context, *IssueParticipantCertificateRequest) (*IssueParticipantCertificateResponse, error)
	SignParticipantCSR(context.Context, *SignParticipantCSRRequest) (*SignParticipantCSRResponse, error)
	ApproveKYC(context.Context, *ApproveKYCRequest) (*ApproveKYCResponse, error)
	ManageParticipantStatus(context.Context, *ManageParticipantStatusRequest) (*ManageParticipantStatusResponse, error)
	GetCircuitBreakerStatus(context.Context, *emptypb.Empty) (*GetCircuitBreakerStatusResponse, error)
	ToggleCircuitBreaker(context.Context, *ToggleCircuitBreakerRequest) (*ToggleCircuitBreakerResponse, error)
	GetSystemParameters(context.Context, *emptypb.Empty) (*GetSystemParametersResponse, error)
	UpdateSystemParameters(context.Context, *UpdateSystemParametersRequest) (*UpdateSystemParametersResponse, error)
}

// UnimplementedComplianceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplianceServiceServer struct{}

func (UnimplementedComplianceServiceServer) UpsertParticipant(context.Context, *UpsertParticipantRequest) (*UpsertParticipantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertParticipant not implemented")
}
func (UnimplementedComplianceServiceServer) GetParticipantByUser(context.Context, *GetParticipantByUserRequest) (*GetParticipantByUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParticipantByUser not implemented")
}
func (UnimplementedComplianceServiceServer) ListParticipants(context.Context, *ListParticipantsRequest) (*ListParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParticipants not implemented")
}
func (UnimplementedComplianceServiceServer) CreateAuditLog(context.Context, *CreateAuditLogRequest) (*CreateAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuditLog not implemented")
}
func (UnimplementedComplianceServiceServer) GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLogs not implemented")
}
func (UnimplementedComplianceServiceServer) IssueParticipantCertificate(context.Context, *IssueParticipantCertificateRequest) (*IssueParticipantCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueParticipantCertificate not implemented")
}
func (UnimplementedComplianceServiceServer) SignParticipantCSR(context.Context, *SignParticipantCSRRequest) (*SignParticipantCSRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignParticipantCSR not implemented")
}
func (UnimplementedComplianceServiceServer) ApproveKYC(context.Context, *ApproveKYCRequest) (*ApproveKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveKYC not implemented")
}
func (UnimplementedComplianceServiceServer) ManageParticipantStatus(context.Context, *ManageParticipantStatusRequest) (*ManageParticipantStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageParticipantStatus not implemented")
}
func (UnimplementedComplianceServiceServer) GetCircuitBreakerStatus(context.Context, *emptypb.Empty) (*GetCircuitBreakerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCircuitBreakerStatus not implemented")
}
func (UnimplementedComplianceServiceServer) ToggleCircuitBreaker(context.Context, *ToggleCircuitBreakerRequest) (*ToggleCircuitBreakerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleCircuitBreaker not implemented")
}
func (UnimplementedComplianceServiceServer) GetSystemParameters(context.Context, *emptypb.Empty) (*GetSystemParametersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemParameters not implemented")
}
func (UnimplementedComplianceServiceServer) UpdateSystemParameters(context.Context, *UpdateSystemParametersRequest) (*UpdateSystemParametersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSystemParameters not implemented")
}
func (UnimplementedComplianceServiceServer) testEmbeddedByValue() {}

// UnsafeComplianceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplianceServiceServer will
// result in compilation errors.
type UnsafeComplianceServiceServer interface {
	mustEmbedUnimplementedComplianceServiceServer()
}

func RegisterComplianceServiceServer(s grpc.ServiceRegistrar, srv ComplianceServiceServer) {
	// If the following call panics, it indicates UnimplementedComplianceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComplianceService_ServiceDesc, srv)
}

func _ComplianceService_UpsertParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).UpsertParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_UpsertParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).UpsertParticipant(ctx, req.(*UpsertParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_GetParticipantByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).GetParticipantByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_GetParticipantByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).GetParticipantByUser(ctx, req.(*GetParticipantByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_ListParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).ListParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_ListParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).ListParticipants(ctx, req.(*ListParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_CreateAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).CreateAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_CreateAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).CreateAuditLog(ctx, req.(*CreateAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_GetAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).GetAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_GetAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).GetAuditLogs(ctx, req.(*GetAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_IssueParticipantCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueParticipantCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).IssueParticipantCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_IssueParticipantCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).IssueParticipantCertificate(ctx, req.(*IssueParticipantCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_SignParticipantCSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignParticipantCSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).SignParticipantCSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_SignParticipantCSR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).SignParticipantCSR(ctx, req.(*SignParticipantCSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_ApproveKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).ApproveKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_ApproveKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).ApproveKYC(ctx, req.(*ApproveKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_ManageParticipantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageParticipantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).ManageParticipantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_ManageParticipantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).ManageParticipantStatus(ctx, req.(*ManageParticipantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_GetCircuitBreakerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).GetCircuitBreakerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_GetCircuitBreakerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).GetCircuitBreakerStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_ToggleCircuitBreaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleCircuitBreakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).ToggleCircuitBreaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_ToggleCircuitBreaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).ToggleCircuitBreaker(ctx, req.(*ToggleCircuitBreakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_GetSystemParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).GetSystemParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_GetSystemParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).GetSystemParameters(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_UpdateSystemParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).UpdateSystemParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_UpdateSystemParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).UpdateSystemParameters(ctx, req.(*UpdateSystemParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComplianceService_ServiceDesc is the grpc.ServiceDesc for ComplianceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComplianceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compliance.v1.ComplianceService",
	HandlerType: (*ComplianceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertParticipant",
			Handler:    _ComplianceService_UpsertParticipant_Handler,
		},
		{
			MethodName: "GetParticipantByUser",
			Handler:    _ComplianceService_GetParticipantByUser_Handler,
		},
		{
			MethodName: "ListParticipants",
			Handler:    _ComplianceService_ListParticipants_Handler,
		},
		{
			MethodName: "CreateAuditLog",
			Handler:    _ComplianceService_CreateAuditLog_Handler,
		},
		{
			MethodName: "GetAuditLogs",
			Handler:    _ComplianceService_GetAuditLogs_Handler,
		},
		{
			MethodName: "IssueParticipantCertificate",
			Handler:    _ComplianceService_IssueParticipantCertificate_Handler,
		},
		{
			MethodName: "SignParticipantCSR",
			Handler:    _ComplianceService_SignParticipantCSR_Handler,
		},
		{
			MethodName: "ApproveKYC",
			Handler:    _ComplianceService_ApproveKYC_Handler,
		},
		{
			MethodName: "ManageParticipantStatus",
			Handler:    _ComplianceService_ManageParticipantStatus_Handler,
		},
		{
			MethodName: "GetCircuitBreakerStatus",
			Handler:    _ComplianceService_GetCircuitBreakerStatus_Handler,
		},
		{
			MethodName: "ToggleCircuitBreaker",
			Handler:    _ComplianceService_ToggleCircuitBreaker_Handler,
		},
		{
			MethodName: "GetSystemParameters",
			Handler:    _ComplianceService_GetSystemParameters_Handler,
		},
		{
			MethodName: "UpdateSystemParameters",
			Handler:    _ComplianceService_UpdateSystemParameters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compliance/v1/compliance.proto",
}
