// SPDX-License-Identifier: Apache-2.0

import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@cbweb3/ui";
import { useEffect } from "react";
import { useStabilityStore } from "../stores";

export function LiquidityMonitorPage() {
  const { pools, alerts, status, refresh, error } = useStabilityStore();

  useEffect(() => {
    void refresh();
  }, [refresh]);

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Scenario B · Liquidity Stability Monitor</CardTitle>
          <CardDescription>Read-only supervision of pool ratios and imbalance thresholds.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Pair</TableHead>
                <TableHead>Reserve A</TableHead>
                <TableHead>Reserve B</TableHead>
                <TableHead>Ratio</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {pools.map((pool) => (
                <TableRow key={pool.pair}>
                  <TableCell>{pool.pair}</TableCell>
                  <TableCell>{pool.reserveA.toLocaleString()}</TableCell>
                  <TableCell>{pool.reserveB.toLocaleString()}</TableCell>
                  <TableCell>
                    {pool.ratioA}/{pool.ratioB}
                  </TableCell>
                  <TableCell>
                    <Badge variant={pool.isImbalanced ? "destructive" : "success"}>
                      {pool.isImbalanced ? "IMBALANCED" : "HEALTHY"}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          {status === "loading" ? <p className="pt-2 text-sm text-muted-foreground">Refreshing pool health...</p> : null}
          {error ? <p className="pt-2 text-sm text-destructive">{error}</p> : null}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Active Alerts</CardTitle>
          <CardDescription>Imbalance notifications generated by monitor rules.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          {alerts.map((alert) => (
            <div key={alert.id} className="rounded-md border border-border p-2 text-sm">
              <div className="flex items-center justify-between gap-2">
                <span className="font-medium">{alert.pair}</span>
                <Badge variant={alert.severity === "CRITICAL" ? "destructive" : "warning"}>{alert.severity}</Badge>
              </div>
              <p className="text-muted-foreground">{alert.message}</p>
            </div>
          ))}
          {!alerts.length ? <p className="text-sm text-muted-foreground">No active alerts.</p> : null}
        </CardContent>
      </Card>
    </div>
  );
}
