// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v7.34.0
// source: payment_orchestrator/v1/payment_orchestrator.proto

package paymentorchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PaymentOrchestratorService_ProposeFXAgreement_FullMethodName   = "/payment_orchestrator.v1.PaymentOrchestratorService/ProposeFXAgreement"
	PaymentOrchestratorService_AcceptFXAgreement_FullMethodName    = "/payment_orchestrator.v1.PaymentOrchestratorService/AcceptFXAgreement"
	PaymentOrchestratorService_RejectFXAgreement_FullMethodName    = "/payment_orchestrator.v1.PaymentOrchestratorService/RejectFXAgreement"
	PaymentOrchestratorService_CancelFXAgreement_FullMethodName    = "/payment_orchestrator.v1.PaymentOrchestratorService/CancelFXAgreement"
	PaymentOrchestratorService_SettleFXAgreement_FullMethodName    = "/payment_orchestrator.v1.PaymentOrchestratorService/SettleFXAgreement"
	PaymentOrchestratorService_GetFXAgreement_FullMethodName       = "/payment_orchestrator.v1.PaymentOrchestratorService/GetFXAgreement"
	PaymentOrchestratorService_ListFXAgreements_FullMethodName     = "/payment_orchestrator.v1.PaymentOrchestratorService/ListFXAgreements"
	PaymentOrchestratorService_LockHTLC_FullMethodName             = "/payment_orchestrator.v1.PaymentOrchestratorService/LockHTLC"
	PaymentOrchestratorService_LockHTLCWithHashLock_FullMethodName = "/payment_orchestrator.v1.PaymentOrchestratorService/LockHTLCWithHashLock"
	PaymentOrchestratorService_SettleHTLC_FullMethodName           = "/payment_orchestrator.v1.PaymentOrchestratorService/SettleHTLC"
	PaymentOrchestratorService_RefundHTLC_FullMethodName           = "/payment_orchestrator.v1.PaymentOrchestratorService/RefundHTLC"
	PaymentOrchestratorService_GetHTLCStatus_FullMethodName        = "/payment_orchestrator.v1.PaymentOrchestratorService/GetHTLCStatus"
	PaymentOrchestratorService_SearchHTLC_FullMethodName           = "/payment_orchestrator.v1.PaymentOrchestratorService/SearchHTLC"
	PaymentOrchestratorService_MintToken_FullMethodName            = "/payment_orchestrator.v1.PaymentOrchestratorService/MintToken"
	PaymentOrchestratorService_TransferToken_FullMethodName        = "/payment_orchestrator.v1.PaymentOrchestratorService/TransferToken"
	PaymentOrchestratorService_GetBalance_FullMethodName           = "/payment_orchestrator.v1.PaymentOrchestratorService/GetBalance"
)

// PaymentOrchestratorServiceClient is the client API for PaymentOrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentOrchestratorServiceClient interface {
	// FX Agreement lifecycle (mirrors FXAgreement.sol on Besu)
	ProposeFXAgreement(ctx context.Context, in *ProposeFXAgreementRequest, opts ...grpc.CallOption) (*ProposeFXAgreementResponse, error)
	AcceptFXAgreement(ctx context.Context, in *AcceptFXAgreementRequest, opts ...grpc.CallOption) (*AcceptFXAgreementResponse, error)
	RejectFXAgreement(ctx context.Context, in *RejectFXAgreementRequest, opts ...grpc.CallOption) (*RejectFXAgreementResponse, error)
	CancelFXAgreement(ctx context.Context, in *CancelFXAgreementRequest, opts ...grpc.CallOption) (*CancelFXAgreementResponse, error)
	SettleFXAgreement(ctx context.Context, in *SettleFXAgreementRequest, opts ...grpc.CallOption) (*SettleFXAgreementResponse, error)
	GetFXAgreement(ctx context.Context, in *GetFXAgreementRequest, opts ...grpc.CallOption) (*GetFXAgreementResponse, error)
	ListFXAgreements(ctx context.Context, in *ListFXAgreementsRequest, opts ...grpc.CallOption) (*ListFXAgreementsResponse, error)
	// HTLC dual-layer operations (public coordination + private Zeto lock)
	LockHTLC(ctx context.Context, in *LockHTLCRequest, opts ...grpc.CallOption) (*LockHTLCResponse, error)
	LockHTLCWithHashLock(ctx context.Context, in *LockHTLCWithHashLockRequest, opts ...grpc.CallOption) (*LockHTLCWithHashLockResponse, error)
	SettleHTLC(ctx context.Context, in *SettleHTLCRequest, opts ...grpc.CallOption) (*SettleHTLCResponse, error)
	RefundHTLC(ctx context.Context, in *RefundHTLCRequest, opts ...grpc.CallOption) (*RefundHTLCResponse, error)
	GetHTLCStatus(ctx context.Context, in *GetHTLCStatusRequest, opts ...grpc.CallOption) (*GetHTLCStatusResponse, error)
	SearchHTLC(ctx context.Context, in *SearchHTLCRequest, opts ...grpc.CallOption) (*SearchHTLCResponse, error)
	// Token operations (Zeto via Paladin sidecar)
	MintToken(ctx context.Context, in *MintTokenRequest, opts ...grpc.CallOption) (*MintTokenResponse, error)
	TransferToken(ctx context.Context, in *TransferTokenRequest, opts ...grpc.CallOption) (*TransferTokenResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type paymentOrchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentOrchestratorServiceClient(cc grpc.ClientConnInterface) PaymentOrchestratorServiceClient {
	return &paymentOrchestratorServiceClient{cc}
}

func (c *paymentOrchestratorServiceClient) ProposeFXAgreement(ctx context.Context, in *ProposeFXAgreementRequest, opts ...grpc.CallOption) (*ProposeFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ProposeFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) AcceptFXAgreement(ctx context.Context, in *AcceptFXAgreementRequest, opts ...grpc.CallOption) (*AcceptFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_AcceptFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RejectFXAgreement(ctx context.Context, in *RejectFXAgreementRequest, opts ...grpc.CallOption) (*RejectFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RejectFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) CancelFXAgreement(ctx context.Context, in *CancelFXAgreementRequest, opts ...grpc.CallOption) (*CancelFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_CancelFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) SettleFXAgreement(ctx context.Context, in *SettleFXAgreementRequest, opts ...grpc.CallOption) (*SettleFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_SettleFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetFXAgreement(ctx context.Context, in *GetFXAgreementRequest, opts ...grpc.CallOption) (*GetFXAgreementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFXAgreementResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetFXAgreement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) ListFXAgreements(ctx context.Context, in *ListFXAgreementsRequest, opts ...grpc.CallOption) (*ListFXAgreementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFXAgreementsResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_ListFXAgreements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) LockHTLC(ctx context.Context, in *LockHTLCRequest, opts ...grpc.CallOption) (*LockHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_LockHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) LockHTLCWithHashLock(ctx context.Context, in *LockHTLCWithHashLockRequest, opts ...grpc.CallOption) (*LockHTLCWithHashLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockHTLCWithHashLockResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_LockHTLCWithHashLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) SettleHTLC(ctx context.Context, in *SettleHTLCRequest, opts ...grpc.CallOption) (*SettleHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_SettleHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) RefundHTLC(ctx context.Context, in *RefundHTLCRequest, opts ...grpc.CallOption) (*RefundHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_RefundHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetHTLCStatus(ctx context.Context, in *GetHTLCStatusRequest, opts ...grpc.CallOption) (*GetHTLCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHTLCStatusResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetHTLCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) SearchHTLC(ctx context.Context, in *SearchHTLCRequest, opts ...grpc.CallOption) (*SearchHTLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchHTLCResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_SearchHTLC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) MintToken(ctx context.Context, in *MintTokenRequest, opts ...grpc.CallOption) (*MintTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintTokenResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_MintToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) TransferToken(ctx context.Context, in *TransferTokenRequest, opts ...grpc.CallOption) (*TransferTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferTokenResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_TransferToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestratorServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestratorService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentOrchestratorServiceServer is the server API for PaymentOrchestratorService service.
// All implementations should embed UnimplementedPaymentOrchestratorServiceServer
// for forward compatibility
type PaymentOrchestratorServiceServer interface {
	// FX Agreement lifecycle (mirrors FXAgreement.sol on Besu)
	ProposeFXAgreement(context.Context, *ProposeFXAgreementRequest) (*ProposeFXAgreementResponse, error)
	AcceptFXAgreement(context.Context, *AcceptFXAgreementRequest) (*AcceptFXAgreementResponse, error)
	RejectFXAgreement(context.Context, *RejectFXAgreementRequest) (*RejectFXAgreementResponse, error)
	CancelFXAgreement(context.Context, *CancelFXAgreementRequest) (*CancelFXAgreementResponse, error)
	SettleFXAgreement(context.Context, *SettleFXAgreementRequest) (*SettleFXAgreementResponse, error)
	GetFXAgreement(context.Context, *GetFXAgreementRequest) (*GetFXAgreementResponse, error)
	ListFXAgreements(context.Context, *ListFXAgreementsRequest) (*ListFXAgreementsResponse, error)
	// HTLC dual-layer operations (public coordination + private Zeto lock)
	LockHTLC(context.Context, *LockHTLCRequest) (*LockHTLCResponse, error)
	LockHTLCWithHashLock(context.Context, *LockHTLCWithHashLockRequest) (*LockHTLCWithHashLockResponse, error)
	SettleHTLC(context.Context, *SettleHTLCRequest) (*SettleHTLCResponse, error)
	RefundHTLC(context.Context, *RefundHTLCRequest) (*RefundHTLCResponse, error)
	GetHTLCStatus(context.Context, *GetHTLCStatusRequest) (*GetHTLCStatusResponse, error)
	SearchHTLC(context.Context, *SearchHTLCRequest) (*SearchHTLCResponse, error)
	// Token operations (Zeto via Paladin sidecar)
	MintToken(context.Context, *MintTokenRequest) (*MintTokenResponse, error)
	TransferToken(context.Context, *TransferTokenRequest) (*TransferTokenResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
}

// UnimplementedPaymentOrchestratorServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPaymentOrchestratorServiceServer struct {
}

func (UnimplementedPaymentOrchestratorServiceServer) ProposeFXAgreement(context.Context, *ProposeFXAgreementRequest) (*ProposeFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) AcceptFXAgreement(context.Context, *AcceptFXAgreementRequest) (*AcceptFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RejectFXAgreement(context.Context, *RejectFXAgreementRequest) (*RejectFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) CancelFXAgreement(context.Context, *CancelFXAgreementRequest) (*CancelFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) SettleFXAgreement(context.Context, *SettleFXAgreementRequest) (*SettleFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetFXAgreement(context.Context, *GetFXAgreementRequest) (*GetFXAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFXAgreement not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) ListFXAgreements(context.Context, *ListFXAgreementsRequest) (*ListFXAgreementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFXAgreements not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) LockHTLC(context.Context, *LockHTLCRequest) (*LockHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) LockHTLCWithHashLock(context.Context, *LockHTLCWithHashLockRequest) (*LockHTLCWithHashLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockHTLCWithHashLock not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) SettleHTLC(context.Context, *SettleHTLCRequest) (*SettleHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) RefundHTLC(context.Context, *RefundHTLCRequest) (*RefundHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetHTLCStatus(context.Context, *GetHTLCStatusRequest) (*GetHTLCStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHTLCStatus not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) SearchHTLC(context.Context, *SearchHTLCRequest) (*SearchHTLCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHTLC not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) MintToken(context.Context, *MintTokenRequest) (*MintTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintToken not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) TransferToken(context.Context, *TransferTokenRequest) (*TransferTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferToken not implemented")
}
func (UnimplementedPaymentOrchestratorServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}

// UnsafePaymentOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentOrchestratorServiceServer will
// result in compilation errors.
type UnsafePaymentOrchestratorServiceServer interface {
	mustEmbedUnimplementedPaymentOrchestratorServiceServer()
}

func RegisterPaymentOrchestratorServiceServer(s grpc.ServiceRegistrar, srv PaymentOrchestratorServiceServer) {
	s.RegisterService(&PaymentOrchestratorService_ServiceDesc, srv)
}

func _PaymentOrchestratorService_ProposeFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ProposeFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ProposeFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ProposeFXAgreement(ctx, req.(*ProposeFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_AcceptFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).AcceptFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_AcceptFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).AcceptFXAgreement(ctx, req.(*AcceptFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RejectFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RejectFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RejectFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RejectFXAgreement(ctx, req.(*RejectFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_CancelFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).CancelFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_CancelFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).CancelFXAgreement(ctx, req.(*CancelFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_SettleFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).SettleFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_SettleFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).SettleFXAgreement(ctx, req.(*SettleFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetFXAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFXAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetFXAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetFXAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetFXAgreement(ctx, req.(*GetFXAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_ListFXAgreements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFXAgreementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).ListFXAgreements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_ListFXAgreements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).ListFXAgreements(ctx, req.(*ListFXAgreementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_LockHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).LockHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_LockHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).LockHTLC(ctx, req.(*LockHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_LockHTLCWithHashLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockHTLCWithHashLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).LockHTLCWithHashLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_LockHTLCWithHashLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).LockHTLCWithHashLock(ctx, req.(*LockHTLCWithHashLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_SettleHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).SettleHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_SettleHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).SettleHTLC(ctx, req.(*SettleHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_RefundHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).RefundHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_RefundHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).RefundHTLC(ctx, req.(*RefundHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetHTLCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHTLCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetHTLCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetHTLCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetHTLCStatus(ctx, req.(*GetHTLCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_SearchHTLC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHTLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).SearchHTLC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_SearchHTLC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).SearchHTLC(ctx, req.(*SearchHTLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_MintToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).MintToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_MintToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).MintToken(ctx, req.(*MintTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_TransferToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).TransferToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_TransferToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).TransferToken(ctx, req.(*TransferTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestratorService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestratorServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestratorService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestratorServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentOrchestratorService_ServiceDesc is the grpc.ServiceDesc for PaymentOrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentOrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment_orchestrator.v1.PaymentOrchestratorService",
	HandlerType: (*PaymentOrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeFXAgreement",
			Handler:    _PaymentOrchestratorService_ProposeFXAgreement_Handler,
		},
		{
			MethodName: "AcceptFXAgreement",
			Handler:    _PaymentOrchestratorService_AcceptFXAgreement_Handler,
		},
		{
			MethodName: "RejectFXAgreement",
			Handler:    _PaymentOrchestratorService_RejectFXAgreement_Handler,
		},
		{
			MethodName: "CancelFXAgreement",
			Handler:    _PaymentOrchestratorService_CancelFXAgreement_Handler,
		},
		{
			MethodName: "SettleFXAgreement",
			Handler:    _PaymentOrchestratorService_SettleFXAgreement_Handler,
		},
		{
			MethodName: "GetFXAgreement",
			Handler:    _PaymentOrchestratorService_GetFXAgreement_Handler,
		},
		{
			MethodName: "ListFXAgreements",
			Handler:    _PaymentOrchestratorService_ListFXAgreements_Handler,
		},
		{
			MethodName: "LockHTLC",
			Handler:    _PaymentOrchestratorService_LockHTLC_Handler,
		},
		{
			MethodName: "LockHTLCWithHashLock",
			Handler:    _PaymentOrchestratorService_LockHTLCWithHashLock_Handler,
		},
		{
			MethodName: "SettleHTLC",
			Handler:    _PaymentOrchestratorService_SettleHTLC_Handler,
		},
		{
			MethodName: "RefundHTLC",
			Handler:    _PaymentOrchestratorService_RefundHTLC_Handler,
		},
		{
			MethodName: "GetHTLCStatus",
			Handler:    _PaymentOrchestratorService_GetHTLCStatus_Handler,
		},
		{
			MethodName: "SearchHTLC",
			Handler:    _PaymentOrchestratorService_SearchHTLC_Handler,
		},
		{
			MethodName: "MintToken",
			Handler:    _PaymentOrchestratorService_MintToken_Handler,
		},
		{
			MethodName: "TransferToken",
			Handler:    _PaymentOrchestratorService_TransferToken_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PaymentOrchestratorService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_orchestrator/v1/payment_orchestrator.proto",
}
