// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment_orchestrator/v1/payment_orchestrator.proto

package paymentorchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FXAgreementState int32

const (
	FXAgreementState_FX_STATE_INVALID   FXAgreementState = 0
	FXAgreementState_FX_STATE_PROPOSED  FXAgreementState = 1
	FXAgreementState_FX_STATE_ACCEPTED  FXAgreementState = 2
	FXAgreementState_FX_STATE_REJECTED  FXAgreementState = 3
	FXAgreementState_FX_STATE_CANCELLED FXAgreementState = 4
	FXAgreementState_FX_STATE_SETTLED   FXAgreementState = 5
)

// Enum value maps for FXAgreementState.
var (
	FXAgreementState_name = map[int32]string{
		0: "FX_STATE_INVALID",
		1: "FX_STATE_PROPOSED",
		2: "FX_STATE_ACCEPTED",
		3: "FX_STATE_REJECTED",
		4: "FX_STATE_CANCELLED",
		5: "FX_STATE_SETTLED",
	}
	FXAgreementState_value = map[string]int32{
		"FX_STATE_INVALID":   0,
		"FX_STATE_PROPOSED":  1,
		"FX_STATE_ACCEPTED":  2,
		"FX_STATE_REJECTED":  3,
		"FX_STATE_CANCELLED": 4,
		"FX_STATE_SETTLED":   5,
	}
)

func (x FXAgreementState) Enum() *FXAgreementState {
	p := new(FXAgreementState)
	*p = x
	return p
}

func (x FXAgreementState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FXAgreementState) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_enumTypes[0].Descriptor()
}

func (FXAgreementState) Type() protoreflect.EnumType {
	return &file_payment_orchestrator_v1_payment_orchestrator_proto_enumTypes[0]
}

func (x FXAgreementState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FXAgreementState.Descriptor instead.
func (FXAgreementState) EnumDescriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{0}
}

type HTLCState int32

const (
	HTLCState_HTLC_STATE_INVALID  HTLCState = 0
	HTLCState_HTLC_STATE_PENDING  HTLCState = 1
	HTLCState_HTLC_STATE_LOCKED   HTLCState = 2
	HTLCState_HTLC_STATE_SETTLED  HTLCState = 3
	HTLCState_HTLC_STATE_REFUNDED HTLCState = 4
)

// Enum value maps for HTLCState.
var (
	HTLCState_name = map[int32]string{
		0: "HTLC_STATE_INVALID",
		1: "HTLC_STATE_PENDING",
		2: "HTLC_STATE_LOCKED",
		3: "HTLC_STATE_SETTLED",
		4: "HTLC_STATE_REFUNDED",
	}
	HTLCState_value = map[string]int32{
		"HTLC_STATE_INVALID":  0,
		"HTLC_STATE_PENDING":  1,
		"HTLC_STATE_LOCKED":   2,
		"HTLC_STATE_SETTLED":  3,
		"HTLC_STATE_REFUNDED": 4,
	}
)

func (x HTLCState) Enum() *HTLCState {
	p := new(HTLCState)
	*p = x
	return p
}

func (x HTLCState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTLCState) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_enumTypes[1].Descriptor()
}

func (HTLCState) Type() protoreflect.EnumType {
	return &file_payment_orchestrator_v1_payment_orchestrator_proto_enumTypes[1]
}

func (x HTLCState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HTLCState.Descriptor instead.
func (HTLCState) EnumDescriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{1}
}

type FXAgreement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CounterpartyA string                 `protobuf:"bytes,2,opt,name=counterparty_a,json=counterpartyA,proto3" json:"counterparty_a,omitempty"`
	CounterpartyB string                 `protobuf:"bytes,3,opt,name=counterparty_b,json=counterpartyB,proto3" json:"counterparty_b,omitempty"`
	BaseToken     string                 `protobuf:"bytes,4,opt,name=base_token,json=baseToken,proto3" json:"base_token,omitempty"`
	QuoteToken    string                 `protobuf:"bytes,5,opt,name=quote_token,json=quoteToken,proto3" json:"quote_token,omitempty"`
	Notional      string                 `protobuf:"bytes,6,opt,name=notional,proto3" json:"notional,omitempty"`
	Rate          string                 `protobuf:"bytes,7,opt,name=rate,proto3" json:"rate,omitempty"`
	ExpiryDate    uint64                 `protobuf:"varint,8,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	State         FXAgreementState       `protobuf:"varint,9,opt,name=state,proto3,enum=payment_orchestrator.v1.FXAgreementState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FXAgreement) Reset() {
	*x = FXAgreement{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FXAgreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FXAgreement) ProtoMessage() {}

func (x *FXAgreement) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FXAgreement.ProtoReflect.Descriptor instead.
func (*FXAgreement) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *FXAgreement) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *FXAgreement) GetCounterpartyA() string {
	if x != nil {
		return x.CounterpartyA
	}
	return ""
}

func (x *FXAgreement) GetCounterpartyB() string {
	if x != nil {
		return x.CounterpartyB
	}
	return ""
}

func (x *FXAgreement) GetBaseToken() string {
	if x != nil {
		return x.BaseToken
	}
	return ""
}

func (x *FXAgreement) GetQuoteToken() string {
	if x != nil {
		return x.QuoteToken
	}
	return ""
}

func (x *FXAgreement) GetNotional() string {
	if x != nil {
		return x.Notional
	}
	return ""
}

func (x *FXAgreement) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *FXAgreement) GetExpiryDate() uint64 {
	if x != nil {
		return x.ExpiryDate
	}
	return 0
}

func (x *FXAgreement) GetState() FXAgreementState {
	if x != nil {
		return x.State
	}
	return FXAgreementState_FX_STATE_INVALID
}

type ProposeFXAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	CounterpartyB string                 `protobuf:"bytes,2,opt,name=counterparty_b,json=counterpartyB,proto3" json:"counterparty_b,omitempty"`
	BaseToken     string                 `protobuf:"bytes,3,opt,name=base_token,json=baseToken,proto3" json:"base_token,omitempty"`
	QuoteToken    string                 `protobuf:"bytes,4,opt,name=quote_token,json=quoteToken,proto3" json:"quote_token,omitempty"`
	Notional      string                 `protobuf:"bytes,5,opt,name=notional,proto3" json:"notional,omitempty"`
	Rate          string                 `protobuf:"bytes,6,opt,name=rate,proto3" json:"rate,omitempty"`
	ExpiryDate    uint64                 `protobuf:"varint,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeFXAgreementRequest) Reset() {
	*x = ProposeFXAgreementRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeFXAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeFXAgreementRequest) ProtoMessage() {}

func (x *ProposeFXAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeFXAgreementRequest.ProtoReflect.Descriptor instead.
func (*ProposeFXAgreementRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeFXAgreementRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *ProposeFXAgreementRequest) GetCounterpartyB() string {
	if x != nil {
		return x.CounterpartyB
	}
	return ""
}

func (x *ProposeFXAgreementRequest) GetBaseToken() string {
	if x != nil {
		return x.BaseToken
	}
	return ""
}

func (x *ProposeFXAgreementRequest) GetQuoteToken() string {
	if x != nil {
		return x.QuoteToken
	}
	return ""
}

func (x *ProposeFXAgreementRequest) GetNotional() string {
	if x != nil {
		return x.Notional
	}
	return ""
}

func (x *ProposeFXAgreementRequest) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ProposeFXAgreementRequest) GetExpiryDate() uint64 {
	if x != nil {
		return x.ExpiryDate
	}
	return 0
}

type ProposeFXAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TradeId       string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeFXAgreementResponse) Reset() {
	*x = ProposeFXAgreementResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeFXAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeFXAgreementResponse) ProtoMessage() {}

func (x *ProposeFXAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeFXAgreementResponse.ProtoReflect.Descriptor instead.
func (*ProposeFXAgreementResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *ProposeFXAgreementResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ProposeFXAgreementResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type AcceptFXAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFXAgreementRequest) Reset() {
	*x = AcceptFXAgreementRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFXAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFXAgreementRequest) ProtoMessage() {}

func (x *AcceptFXAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFXAgreementRequest.ProtoReflect.Descriptor instead.
func (*AcceptFXAgreementRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptFXAgreementRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type AcceptFXAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFXAgreementResponse) Reset() {
	*x = AcceptFXAgreementResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFXAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFXAgreementResponse) ProtoMessage() {}

func (x *AcceptFXAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFXAgreementResponse.ProtoReflect.Descriptor instead.
func (*AcceptFXAgreementResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptFXAgreementResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type RejectFXAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFXAgreementRequest) Reset() {
	*x = RejectFXAgreementRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFXAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFXAgreementRequest) ProtoMessage() {}

func (x *RejectFXAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFXAgreementRequest.ProtoReflect.Descriptor instead.
func (*RejectFXAgreementRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *RejectFXAgreementRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type RejectFXAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFXAgreementResponse) Reset() {
	*x = RejectFXAgreementResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFXAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFXAgreementResponse) ProtoMessage() {}

func (x *RejectFXAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFXAgreementResponse.ProtoReflect.Descriptor instead.
func (*RejectFXAgreementResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *RejectFXAgreementResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type CancelFXAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFXAgreementRequest) Reset() {
	*x = CancelFXAgreementRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFXAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFXAgreementRequest) ProtoMessage() {}

func (x *CancelFXAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFXAgreementRequest.ProtoReflect.Descriptor instead.
func (*CancelFXAgreementRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *CancelFXAgreementRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type CancelFXAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFXAgreementResponse) Reset() {
	*x = CancelFXAgreementResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFXAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFXAgreementResponse) ProtoMessage() {}

func (x *CancelFXAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFXAgreementResponse.ProtoReflect.Descriptor instead.
func (*CancelFXAgreementResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *CancelFXAgreementResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type SettleFXAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleFXAgreementRequest) Reset() {
	*x = SettleFXAgreementRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleFXAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleFXAgreementRequest) ProtoMessage() {}

func (x *SettleFXAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleFXAgreementRequest.ProtoReflect.Descriptor instead.
func (*SettleFXAgreementRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *SettleFXAgreementRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type SettleFXAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleFXAgreementResponse) Reset() {
	*x = SettleFXAgreementResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleFXAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleFXAgreementResponse) ProtoMessage() {}

func (x *SettleFXAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleFXAgreementResponse.ProtoReflect.Descriptor instead.
func (*SettleFXAgreementResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *SettleFXAgreementResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetFXAgreementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFXAgreementRequest) Reset() {
	*x = GetFXAgreementRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFXAgreementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFXAgreementRequest) ProtoMessage() {}

func (x *GetFXAgreementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFXAgreementRequest.ProtoReflect.Descriptor instead.
func (*GetFXAgreementRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *GetFXAgreementRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type GetFXAgreementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agreement     *FXAgreement           `protobuf:"bytes,1,opt,name=agreement,proto3" json:"agreement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFXAgreementResponse) Reset() {
	*x = GetFXAgreementResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFXAgreementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFXAgreementResponse) ProtoMessage() {}

func (x *GetFXAgreementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFXAgreementResponse.ProtoReflect.Descriptor instead.
func (*GetFXAgreementResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *GetFXAgreementResponse) GetAgreement() *FXAgreement {
	if x != nil {
		return x.Agreement
	}
	return nil
}

type ListFXAgreementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counterparty  string                 `protobuf:"bytes,1,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFXAgreementsRequest) Reset() {
	*x = ListFXAgreementsRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFXAgreementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFXAgreementsRequest) ProtoMessage() {}

func (x *ListFXAgreementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFXAgreementsRequest.ProtoReflect.Descriptor instead.
func (*ListFXAgreementsRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *ListFXAgreementsRequest) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *ListFXAgreementsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListFXAgreementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agreements    []*FXAgreement         `protobuf:"bytes,1,rep,name=agreements,proto3" json:"agreements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFXAgreementsResponse) Reset() {
	*x = ListFXAgreementsResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFXAgreementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFXAgreementsResponse) ProtoMessage() {}

func (x *ListFXAgreementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFXAgreementsResponse.ProtoReflect.Descriptor instead.
func (*ListFXAgreementsResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *ListFXAgreementsResponse) GetAgreements() []*FXAgreement {
	if x != nil {
		return x.Agreements
	}
	return nil
}

type HTLCLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	HashLock      string                 `protobuf:"bytes,4,opt,name=hash_lock,json=hashLock,proto3" json:"hash_lock,omitempty"`
	TimeLock      uint64                 `protobuf:"varint,5,opt,name=time_lock,json=timeLock,proto3" json:"time_lock,omitempty"`
	Secret        string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	ZetoLockRef   string                 `protobuf:"bytes,7,opt,name=zeto_lock_ref,json=zetoLockRef,proto3" json:"zeto_lock_ref,omitempty"`
	State         HTLCState              `protobuf:"varint,8,opt,name=state,proto3,enum=payment_orchestrator.v1.HTLCState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTLCLock) Reset() {
	*x = HTLCLock{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTLCLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTLCLock) ProtoMessage() {}

func (x *HTLCLock) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTLCLock.ProtoReflect.Descriptor instead.
func (*HTLCLock) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{15}
}

func (x *HTLCLock) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *HTLCLock) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *HTLCLock) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *HTLCLock) GetHashLock() string {
	if x != nil {
		return x.HashLock
	}
	return ""
}

func (x *HTLCLock) GetTimeLock() uint64 {
	if x != nil {
		return x.TimeLock
	}
	return 0
}

func (x *HTLCLock) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *HTLCLock) GetZetoLockRef() string {
	if x != nil {
		return x.ZetoLockRef
	}
	return ""
}

func (x *HTLCLock) GetState() HTLCState {
	if x != nil {
		return x.State
	}
	return HTLCState_HTLC_STATE_INVALID
}

type LockHTLCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgreementId   string                 `protobuf:"bytes,1,opt,name=agreement_id,json=agreementId,proto3" json:"agreement_id,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TimeLock      uint64                 `protobuf:"varint,4,opt,name=time_lock,json=timeLock,proto3" json:"time_lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHTLCRequest) Reset() {
	*x = LockHTLCRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHTLCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHTLCRequest) ProtoMessage() {}

func (x *LockHTLCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHTLCRequest.ProtoReflect.Descriptor instead.
func (*LockHTLCRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *LockHTLCRequest) GetAgreementId() string {
	if x != nil {
		return x.AgreementId
	}
	return ""
}

func (x *LockHTLCRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *LockHTLCRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LockHTLCRequest) GetTimeLock() uint64 {
	if x != nil {
		return x.TimeLock
	}
	return 0
}

type LockHTLCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	HashLock      string                 `protobuf:"bytes,2,opt,name=hash_lock,json=hashLock,proto3" json:"hash_lock,omitempty"`
	HtlcTxHash    string                 `protobuf:"bytes,3,opt,name=htlc_tx_hash,json=htlcTxHash,proto3" json:"htlc_tx_hash,omitempty"`
	ZetoTxHash    string                 `protobuf:"bytes,4,opt,name=zeto_tx_hash,json=zetoTxHash,proto3" json:"zeto_tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockHTLCResponse) Reset() {
	*x = LockHTLCResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockHTLCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockHTLCResponse) ProtoMessage() {}

func (x *LockHTLCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockHTLCResponse.ProtoReflect.Descriptor instead.
func (*LockHTLCResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *LockHTLCResponse) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *LockHTLCResponse) GetHashLock() string {
	if x != nil {
		return x.HashLock
	}
	return ""
}

func (x *LockHTLCResponse) GetHtlcTxHash() string {
	if x != nil {
		return x.HtlcTxHash
	}
	return ""
}

func (x *LockHTLCResponse) GetZetoTxHash() string {
	if x != nil {
		return x.ZetoTxHash
	}
	return ""
}

type SettleHTLCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleHTLCRequest) Reset() {
	*x = SettleHTLCRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleHTLCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleHTLCRequest) ProtoMessage() {}

func (x *SettleHTLCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleHTLCRequest.ProtoReflect.Descriptor instead.
func (*SettleHTLCRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{18}
}

func (x *SettleHTLCRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *SettleHTLCRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type SettleHTLCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HtlcTxHash    string                 `protobuf:"bytes,1,opt,name=htlc_tx_hash,json=htlcTxHash,proto3" json:"htlc_tx_hash,omitempty"`
	ZetoTxHash    string                 `protobuf:"bytes,2,opt,name=zeto_tx_hash,json=zetoTxHash,proto3" json:"zeto_tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleHTLCResponse) Reset() {
	*x = SettleHTLCResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleHTLCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleHTLCResponse) ProtoMessage() {}

func (x *SettleHTLCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleHTLCResponse.ProtoReflect.Descriptor instead.
func (*SettleHTLCResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{19}
}

func (x *SettleHTLCResponse) GetHtlcTxHash() string {
	if x != nil {
		return x.HtlcTxHash
	}
	return ""
}

func (x *SettleHTLCResponse) GetZetoTxHash() string {
	if x != nil {
		return x.ZetoTxHash
	}
	return ""
}

type RefundHTLCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundHTLCRequest) Reset() {
	*x = RefundHTLCRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundHTLCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundHTLCRequest) ProtoMessage() {}

func (x *RefundHTLCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundHTLCRequest.ProtoReflect.Descriptor instead.
func (*RefundHTLCRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{20}
}

func (x *RefundHTLCRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type RefundHTLCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HtlcTxHash    string                 `protobuf:"bytes,1,opt,name=htlc_tx_hash,json=htlcTxHash,proto3" json:"htlc_tx_hash,omitempty"`
	ZetoTxHash    string                 `protobuf:"bytes,2,opt,name=zeto_tx_hash,json=zetoTxHash,proto3" json:"zeto_tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundHTLCResponse) Reset() {
	*x = RefundHTLCResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundHTLCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundHTLCResponse) ProtoMessage() {}

func (x *RefundHTLCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundHTLCResponse.ProtoReflect.Descriptor instead.
func (*RefundHTLCResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{21}
}

func (x *RefundHTLCResponse) GetHtlcTxHash() string {
	if x != nil {
		return x.HtlcTxHash
	}
	return ""
}

func (x *RefundHTLCResponse) GetZetoTxHash() string {
	if x != nil {
		return x.ZetoTxHash
	}
	return ""
}

type GetHTLCStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHTLCStatusRequest) Reset() {
	*x = GetHTLCStatusRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHTLCStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHTLCStatusRequest) ProtoMessage() {}

func (x *GetHTLCStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHTLCStatusRequest.ProtoReflect.Descriptor instead.
func (*GetHTLCStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{22}
}

func (x *GetHTLCStatusRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type GetHTLCStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *HTLCLock              `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHTLCStatusResponse) Reset() {
	*x = GetHTLCStatusResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHTLCStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHTLCStatusResponse) ProtoMessage() {}

func (x *GetHTLCStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHTLCStatusResponse.ProtoReflect.Descriptor instead.
func (*GetHTLCStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{23}
}

func (x *GetHTLCStatusResponse) GetLock() *HTLCLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type SearchHTLCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgreementId   string                 `protobuf:"bytes,1,opt,name=agreement_id,json=agreementId,proto3" json:"agreement_id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHTLCRequest) Reset() {
	*x = SearchHTLCRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHTLCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHTLCRequest) ProtoMessage() {}

func (x *SearchHTLCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHTLCRequest.ProtoReflect.Descriptor instead.
func (*SearchHTLCRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{24}
}

func (x *SearchHTLCRequest) GetAgreementId() string {
	if x != nil {
		return x.AgreementId
	}
	return ""
}

func (x *SearchHTLCRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SearchHTLCRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SearchHTLCRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SearchHTLCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locks         []*HTLCLock            `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHTLCResponse) Reset() {
	*x = SearchHTLCResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHTLCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHTLCResponse) ProtoMessage() {}

func (x *SearchHTLCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHTLCResponse.ProtoReflect.Descriptor instead.
func (*SearchHTLCResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{25}
}

func (x *SearchHTLCResponse) GetLocks() []*HTLCLock {
	if x != nil {
		return x.Locks
	}
	return nil
}

type MintTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenRequest) Reset() {
	*x = MintTokenRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenRequest) ProtoMessage() {}

func (x *MintTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenRequest.ProtoReflect.Descriptor instead.
func (*MintTokenRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{26}
}

func (x *MintTokenRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MintTokenRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MintTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenResponse) Reset() {
	*x = MintTokenResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenResponse) ProtoMessage() {}

func (x *MintTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenResponse.ProtoReflect.Descriptor instead.
func (*MintTokenResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{27}
}

func (x *MintTokenResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type TransferTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTokenRequest) Reset() {
	*x = TransferTokenRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenRequest) ProtoMessage() {}

func (x *TransferTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenRequest.ProtoReflect.Descriptor instead.
func (*TransferTokenRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{28}
}

func (x *TransferTokenRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferTokenRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type TransferTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTokenResponse) Reset() {
	*x = TransferTokenResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenResponse) ProtoMessage() {}

func (x *TransferTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenResponse.ProtoReflect.Descriptor instead.
func (*TransferTokenResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{29}
}

func (x *TransferTokenResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{30}
}

func (x *GetBalanceRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP(), []int{31}
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_payment_orchestrator_v1_payment_orchestrator_proto protoreflect.FileDescriptor

const file_payment_orchestrator_v1_payment_orchestrator_proto_rawDesc = "" +
	"\n" +
	"2payment_orchestrator/v1/payment_orchestrator.proto\x12\x17payment_orchestrator.v1\"\xc8\x02\n" +
	"\vFXAgreement\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12%\n" +
	"\x0ecounterparty_a\x18\x02 \x01(\tR\rcounterpartyA\x12%\n" +
	"\x0ecounterparty_b\x18\x03 \x01(\tR\rcounterpartyB\x12\x1d\n" +
	"\n" +
	"base_token\x18\x04 \x01(\tR\tbaseToken\x12\x1f\n" +
	"\vquote_token\x18\x05 \x01(\tR\n" +
	"quoteToken\x12\x1a\n" +
	"\bnotional\x18\x06 \x01(\tR\bnotional\x12\x12\n" +
	"\x04rate\x18\a \x01(\tR\x04rate\x12\x1f\n" +
	"\vexpiry_date\x18\b \x01(\x04R\n" +
	"expiryDate\x12?\n" +
	"\x05state\x18\t \x01(\x0e2).payment_orchestrator.v1.FXAgreementStateR\x05state\"\xee\x01\n" +
	"\x19ProposeFXAgreementRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12%\n" +
	"\x0ecounterparty_b\x18\x02 \x01(\tR\rcounterpartyB\x12\x1d\n" +
	"\n" +
	"base_token\x18\x03 \x01(\tR\tbaseToken\x12\x1f\n" +
	"\vquote_token\x18\x04 \x01(\tR\n" +
	"quoteToken\x12\x1a\n" +
	"\bnotional\x18\x05 \x01(\tR\bnotional\x12\x12\n" +
	"\x04rate\x18\x06 \x01(\tR\x04rate\x12\x1f\n" +
	"\vexpiry_date\x18\a \x01(\x04R\n" +
	"expiryDate\"P\n" +
	"\x1aProposeFXAgreementResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\"5\n" +
	"\x18AcceptFXAgreementRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\"4\n" +
	"\x19AcceptFXAgreementResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"5\n" +
	"\x18RejectFXAgreementRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\"4\n" +
	"\x19RejectFXAgreementResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"5\n" +
	"\x18CancelFXAgreementRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\"4\n" +
	"\x19CancelFXAgreementResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"5\n" +
	"\x18SettleFXAgreementRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\"4\n" +
	"\x19SettleFXAgreementResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"2\n" +
	"\x15GetFXAgreementRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\"\\\n" +
	"\x16GetFXAgreementResponse\x12B\n" +
	"\tagreement\x18\x01 \x01(\v2$.payment_orchestrator.v1.FXAgreementR\tagreement\"S\n" +
	"\x17ListFXAgreementsRequest\x12\"\n" +
	"\fcounterparty\x18\x01 \x01(\tR\fcounterparty\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"`\n" +
	"\x18ListFXAgreementsResponse\x12D\n" +
	"\n" +
	"agreements\x18\x01 \x03(\v2$.payment_orchestrator.v1.FXAgreementR\n" +
	"agreements\"\x8f\x02\n" +
	"\bHTLCLock\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x1b\n" +
	"\thash_lock\x18\x04 \x01(\tR\bhashLock\x12\x1b\n" +
	"\ttime_lock\x18\x05 \x01(\x04R\btimeLock\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\x12\"\n" +
	"\rzeto_lock_ref\x18\a \x01(\tR\vzetoLockRef\x128\n" +
	"\x05state\x18\b \x01(\x0e2\".payment_orchestrator.v1.HTLCStateR\x05state\"\x85\x01\n" +
	"\x0fLockHTLCRequest\x12!\n" +
	"\fagreement_id\x18\x01 \x01(\tR\vagreementId\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1b\n" +
	"\ttime_lock\x18\x04 \x01(\x04R\btimeLock\"\x94\x01\n" +
	"\x10LockHTLCResponse\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x1b\n" +
	"\thash_lock\x18\x02 \x01(\tR\bhashLock\x12 \n" +
	"\fhtlc_tx_hash\x18\x03 \x01(\tR\n" +
	"htlcTxHash\x12 \n" +
	"\fzeto_tx_hash\x18\x04 \x01(\tR\n" +
	"zetoTxHash\"L\n" +
	"\x11SettleHTLCRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"X\n" +
	"\x12SettleHTLCResponse\x12 \n" +
	"\fhtlc_tx_hash\x18\x01 \x01(\tR\n" +
	"htlcTxHash\x12 \n" +
	"\fzeto_tx_hash\x18\x02 \x01(\tR\n" +
	"zetoTxHash\"4\n" +
	"\x11RefundHTLCRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\"X\n" +
	"\x12RefundHTLCResponse\x12 \n" +
	"\fhtlc_tx_hash\x18\x01 \x01(\tR\n" +
	"htlcTxHash\x12 \n" +
	"\fzeto_tx_hash\x18\x02 \x01(\tR\n" +
	"zetoTxHash\"7\n" +
	"\x14GetHTLCStatusRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\"N\n" +
	"\x15GetHTLCStatusResponse\x125\n" +
	"\x04lock\x18\x01 \x01(\v2!.payment_orchestrator.v1.HTLCLockR\x04lock\"\x80\x01\n" +
	"\x11SearchHTLCRequest\x12!\n" +
	"\fagreement_id\x18\x01 \x01(\tR\vagreementId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"M\n" +
	"\x12SearchHTLCResponse\x127\n" +
	"\x05locks\x18\x01 \x03(\v2!.payment_orchestrator.v1.HTLCLockR\x05locks\":\n" +
	"\x10MintTokenRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\",\n" +
	"\x11MintTokenResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\">\n" +
	"\x14TransferTokenRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"0\n" +
	"\x15TransferTokenResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"/\n" +
	"\x11GetBalanceRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance*\x9b\x01\n" +
	"\x10FXAgreementState\x12\x14\n" +
	"\x10FX_STATE_INVALID\x10\x00\x12\x15\n" +
	"\x11FX_STATE_PROPOSED\x10\x01\x12\x15\n" +
	"\x11FX_STATE_ACCEPTED\x10\x02\x12\x15\n" +
	"\x11FX_STATE_REJECTED\x10\x03\x12\x16\n" +
	"\x12FX_STATE_CANCELLED\x10\x04\x12\x14\n" +
	"\x10FX_STATE_SETTLED\x10\x05*\x83\x01\n" +
	"\tHTLCState\x12\x16\n" +
	"\x12HTLC_STATE_INVALID\x10\x00\x12\x16\n" +
	"\x12HTLC_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11HTLC_STATE_LOCKED\x10\x02\x12\x16\n" +
	"\x12HTLC_STATE_SETTLED\x10\x03\x12\x17\n" +
	"\x13HTLC_STATE_REFUNDED\x10\x042\xb8\r\n" +
	"\x1aPaymentOrchestratorService\x12}\n" +
	"\x12ProposeFXAgreement\x122.payment_orchestrator.v1.ProposeFXAgreementRequest\x1a3.payment_orchestrator.v1.ProposeFXAgreementResponse\x12z\n" +
	"\x11AcceptFXAgreement\x121.payment_orchestrator.v1.AcceptFXAgreementRequest\x1a2.payment_orchestrator.v1.AcceptFXAgreementResponse\x12z\n" +
	"\x11RejectFXAgreement\x121.payment_orchestrator.v1.RejectFXAgreementRequest\x1a2.payment_orchestrator.v1.RejectFXAgreementResponse\x12z\n" +
	"\x11CancelFXAgreement\x121.payment_orchestrator.v1.CancelFXAgreementRequest\x1a2.payment_orchestrator.v1.CancelFXAgreementResponse\x12z\n" +
	"\x11SettleFXAgreement\x121.payment_orchestrator.v1.SettleFXAgreementRequest\x1a2.payment_orchestrator.v1.SettleFXAgreementResponse\x12q\n" +
	"\x0eGetFXAgreement\x12..payment_orchestrator.v1.GetFXAgreementRequest\x1a/.payment_orchestrator.v1.GetFXAgreementResponse\x12w\n" +
	"\x10ListFXAgreements\x120.payment_orchestrator.v1.ListFXAgreementsRequest\x1a1.payment_orchestrator.v1.ListFXAgreementsResponse\x12_\n" +
	"\bLockHTLC\x12(.payment_orchestrator.v1.LockHTLCRequest\x1a).payment_orchestrator.v1.LockHTLCResponse\x12e\n" +
	"\n" +
	"SettleHTLC\x12*.payment_orchestrator.v1.SettleHTLCRequest\x1a+.payment_orchestrator.v1.SettleHTLCResponse\x12e\n" +
	"\n" +
	"RefundHTLC\x12*.payment_orchestrator.v1.RefundHTLCRequest\x1a+.payment_orchestrator.v1.RefundHTLCResponse\x12n\n" +
	"\rGetHTLCStatus\x12-.payment_orchestrator.v1.GetHTLCStatusRequest\x1a..payment_orchestrator.v1.GetHTLCStatusResponse\x12e\n" +
	"\n" +
	"SearchHTLC\x12*.payment_orchestrator.v1.SearchHTLCRequest\x1a+.payment_orchestrator.v1.SearchHTLCResponse\x12b\n" +
	"\tMintToken\x12).payment_orchestrator.v1.MintTokenRequest\x1a*.payment_orchestrator.v1.MintTokenResponse\x12n\n" +
	"\rTransferToken\x12-.payment_orchestrator.v1.TransferTokenRequest\x1a..payment_orchestrator.v1.TransferTokenResponse\x12e\n" +
	"\n" +
	"GetBalance\x12*.payment_orchestrator.v1.GetBalanceRequest\x1a+.payment_orchestrator.v1.GetBalanceResponseBnZlgithub.com/LACNetNetworks/cbweb3-platform/backend/shared/proto/payment_orchestrator/v1;paymentorchestratorv1b\x06proto3"

var (
	file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescOnce sync.Once
	file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescData []byte
)

func file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescGZIP() []byte {
	file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescOnce.Do(func() {
		file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_orchestrator_v1_payment_orchestrator_proto_rawDesc), len(file_payment_orchestrator_v1_payment_orchestrator_proto_rawDesc)))
	})
	return file_payment_orchestrator_v1_payment_orchestrator_proto_rawDescData
}

var file_payment_orchestrator_v1_payment_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_payment_orchestrator_v1_payment_orchestrator_proto_goTypes = []any{
	(FXAgreementState)(0),              // 0: payment_orchestrator.v1.FXAgreementState
	(HTLCState)(0),                     // 1: payment_orchestrator.v1.HTLCState
	(*FXAgreement)(nil),                // 2: payment_orchestrator.v1.FXAgreement
	(*ProposeFXAgreementRequest)(nil),  // 3: payment_orchestrator.v1.ProposeFXAgreementRequest
	(*ProposeFXAgreementResponse)(nil), // 4: payment_orchestrator.v1.ProposeFXAgreementResponse
	(*AcceptFXAgreementRequest)(nil),   // 5: payment_orchestrator.v1.AcceptFXAgreementRequest
	(*AcceptFXAgreementResponse)(nil),  // 6: payment_orchestrator.v1.AcceptFXAgreementResponse
	(*RejectFXAgreementRequest)(nil),   // 7: payment_orchestrator.v1.RejectFXAgreementRequest
	(*RejectFXAgreementResponse)(nil),  // 8: payment_orchestrator.v1.RejectFXAgreementResponse
	(*CancelFXAgreementRequest)(nil),   // 9: payment_orchestrator.v1.CancelFXAgreementRequest
	(*CancelFXAgreementResponse)(nil),  // 10: payment_orchestrator.v1.CancelFXAgreementResponse
	(*SettleFXAgreementRequest)(nil),   // 11: payment_orchestrator.v1.SettleFXAgreementRequest
	(*SettleFXAgreementResponse)(nil),  // 12: payment_orchestrator.v1.SettleFXAgreementResponse
	(*GetFXAgreementRequest)(nil),      // 13: payment_orchestrator.v1.GetFXAgreementRequest
	(*GetFXAgreementResponse)(nil),     // 14: payment_orchestrator.v1.GetFXAgreementResponse
	(*ListFXAgreementsRequest)(nil),    // 15: payment_orchestrator.v1.ListFXAgreementsRequest
	(*ListFXAgreementsResponse)(nil),   // 16: payment_orchestrator.v1.ListFXAgreementsResponse
	(*HTLCLock)(nil),                   // 17: payment_orchestrator.v1.HTLCLock
	(*LockHTLCRequest)(nil),            // 18: payment_orchestrator.v1.LockHTLCRequest
	(*LockHTLCResponse)(nil),           // 19: payment_orchestrator.v1.LockHTLCResponse
	(*SettleHTLCRequest)(nil),          // 20: payment_orchestrator.v1.SettleHTLCRequest
	(*SettleHTLCResponse)(nil),         // 21: payment_orchestrator.v1.SettleHTLCResponse
	(*RefundHTLCRequest)(nil),          // 22: payment_orchestrator.v1.RefundHTLCRequest
	(*RefundHTLCResponse)(nil),         // 23: payment_orchestrator.v1.RefundHTLCResponse
	(*GetHTLCStatusRequest)(nil),       // 24: payment_orchestrator.v1.GetHTLCStatusRequest
	(*GetHTLCStatusResponse)(nil),      // 25: payment_orchestrator.v1.GetHTLCStatusResponse
	(*SearchHTLCRequest)(nil),          // 26: payment_orchestrator.v1.SearchHTLCRequest
	(*SearchHTLCResponse)(nil),         // 27: payment_orchestrator.v1.SearchHTLCResponse
	(*MintTokenRequest)(nil),           // 28: payment_orchestrator.v1.MintTokenRequest
	(*MintTokenResponse)(nil),          // 29: payment_orchestrator.v1.MintTokenResponse
	(*TransferTokenRequest)(nil),       // 30: payment_orchestrator.v1.TransferTokenRequest
	(*TransferTokenResponse)(nil),      // 31: payment_orchestrator.v1.TransferTokenResponse
	(*GetBalanceRequest)(nil),          // 32: payment_orchestrator.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),         // 33: payment_orchestrator.v1.GetBalanceResponse
}
var file_payment_orchestrator_v1_payment_orchestrator_proto_depIdxs = []int32{
	0,  // 0: payment_orchestrator.v1.FXAgreement.state:type_name -> payment_orchestrator.v1.FXAgreementState
	2,  // 1: payment_orchestrator.v1.GetFXAgreementResponse.agreement:type_name -> payment_orchestrator.v1.FXAgreement
	2,  // 2: payment_orchestrator.v1.ListFXAgreementsResponse.agreements:type_name -> payment_orchestrator.v1.FXAgreement
	1,  // 3: payment_orchestrator.v1.HTLCLock.state:type_name -> payment_orchestrator.v1.HTLCState
	17, // 4: payment_orchestrator.v1.GetHTLCStatusResponse.lock:type_name -> payment_orchestrator.v1.HTLCLock
	17, // 5: payment_orchestrator.v1.SearchHTLCResponse.locks:type_name -> payment_orchestrator.v1.HTLCLock
	3,  // 6: payment_orchestrator.v1.PaymentOrchestratorService.ProposeFXAgreement:input_type -> payment_orchestrator.v1.ProposeFXAgreementRequest
	5,  // 7: payment_orchestrator.v1.PaymentOrchestratorService.AcceptFXAgreement:input_type -> payment_orchestrator.v1.AcceptFXAgreementRequest
	7,  // 8: payment_orchestrator.v1.PaymentOrchestratorService.RejectFXAgreement:input_type -> payment_orchestrator.v1.RejectFXAgreementRequest
	9,  // 9: payment_orchestrator.v1.PaymentOrchestratorService.CancelFXAgreement:input_type -> payment_orchestrator.v1.CancelFXAgreementRequest
	11, // 10: payment_orchestrator.v1.PaymentOrchestratorService.SettleFXAgreement:input_type -> payment_orchestrator.v1.SettleFXAgreementRequest
	13, // 11: payment_orchestrator.v1.PaymentOrchestratorService.GetFXAgreement:input_type -> payment_orchestrator.v1.GetFXAgreementRequest
	15, // 12: payment_orchestrator.v1.PaymentOrchestratorService.ListFXAgreements:input_type -> payment_orchestrator.v1.ListFXAgreementsRequest
	18, // 13: payment_orchestrator.v1.PaymentOrchestratorService.LockHTLC:input_type -> payment_orchestrator.v1.LockHTLCRequest
	20, // 14: payment_orchestrator.v1.PaymentOrchestratorService.SettleHTLC:input_type -> payment_orchestrator.v1.SettleHTLCRequest
	22, // 15: payment_orchestrator.v1.PaymentOrchestratorService.RefundHTLC:input_type -> payment_orchestrator.v1.RefundHTLCRequest
	24, // 16: payment_orchestrator.v1.PaymentOrchestratorService.GetHTLCStatus:input_type -> payment_orchestrator.v1.GetHTLCStatusRequest
	26, // 17: payment_orchestrator.v1.PaymentOrchestratorService.SearchHTLC:input_type -> payment_orchestrator.v1.SearchHTLCRequest
	28, // 18: payment_orchestrator.v1.PaymentOrchestratorService.MintToken:input_type -> payment_orchestrator.v1.MintTokenRequest
	30, // 19: payment_orchestrator.v1.PaymentOrchestratorService.TransferToken:input_type -> payment_orchestrator.v1.TransferTokenRequest
	32, // 20: payment_orchestrator.v1.PaymentOrchestratorService.GetBalance:input_type -> payment_orchestrator.v1.GetBalanceRequest
	4,  // 21: payment_orchestrator.v1.PaymentOrchestratorService.ProposeFXAgreement:output_type -> payment_orchestrator.v1.ProposeFXAgreementResponse
	6,  // 22: payment_orchestrator.v1.PaymentOrchestratorService.AcceptFXAgreement:output_type -> payment_orchestrator.v1.AcceptFXAgreementResponse
	8,  // 23: payment_orchestrator.v1.PaymentOrchestratorService.RejectFXAgreement:output_type -> payment_orchestrator.v1.RejectFXAgreementResponse
	10, // 24: payment_orchestrator.v1.PaymentOrchestratorService.CancelFXAgreement:output_type -> payment_orchestrator.v1.CancelFXAgreementResponse
	12, // 25: payment_orchestrator.v1.PaymentOrchestratorService.SettleFXAgreement:output_type -> payment_orchestrator.v1.SettleFXAgreementResponse
	14, // 26: payment_orchestrator.v1.PaymentOrchestratorService.GetFXAgreement:output_type -> payment_orchestrator.v1.GetFXAgreementResponse
	16, // 27: payment_orchestrator.v1.PaymentOrchestratorService.ListFXAgreements:output_type -> payment_orchestrator.v1.ListFXAgreementsResponse
	19, // 28: payment_orchestrator.v1.PaymentOrchestratorService.LockHTLC:output_type -> payment_orchestrator.v1.LockHTLCResponse
	21, // 29: payment_orchestrator.v1.PaymentOrchestratorService.SettleHTLC:output_type -> payment_orchestrator.v1.SettleHTLCResponse
	23, // 30: payment_orchestrator.v1.PaymentOrchestratorService.RefundHTLC:output_type -> payment_orchestrator.v1.RefundHTLCResponse
	25, // 31: payment_orchestrator.v1.PaymentOrchestratorService.GetHTLCStatus:output_type -> payment_orchestrator.v1.GetHTLCStatusResponse
	27, // 32: payment_orchestrator.v1.PaymentOrchestratorService.SearchHTLC:output_type -> payment_orchestrator.v1.SearchHTLCResponse
	29, // 33: payment_orchestrator.v1.PaymentOrchestratorService.MintToken:output_type -> payment_orchestrator.v1.MintTokenResponse
	31, // 34: payment_orchestrator.v1.PaymentOrchestratorService.TransferToken:output_type -> payment_orchestrator.v1.TransferTokenResponse
	33, // 35: payment_orchestrator.v1.PaymentOrchestratorService.GetBalance:output_type -> payment_orchestrator.v1.GetBalanceResponse
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_payment_orchestrator_v1_payment_orchestrator_proto_init() }
func file_payment_orchestrator_v1_payment_orchestrator_proto_init() {
	if File_payment_orchestrator_v1_payment_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_orchestrator_v1_payment_orchestrator_proto_rawDesc), len(file_payment_orchestrator_v1_payment_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_orchestrator_v1_payment_orchestrator_proto_goTypes,
		DependencyIndexes: file_payment_orchestrator_v1_payment_orchestrator_proto_depIdxs,
		EnumInfos:         file_payment_orchestrator_v1_payment_orchestrator_proto_enumTypes,
		MessageInfos:      file_payment_orchestrator_v1_payment_orchestrator_proto_msgTypes,
	}.Build()
	File_payment_orchestrator_v1_payment_orchestrator_proto = out.File
	file_payment_orchestrator_v1_payment_orchestrator_proto_goTypes = nil
	file_payment_orchestrator_v1_payment_orchestrator_proto_depIdxs = nil
}
